;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 24/06/2010 00:06:35
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0753	$	_delay_1us:
;delays.ppas,11 :: 		begin
;delays.ppas,12 :: 		Delay_us(1);
$0753	$0000			NOP
$0754	$	delays_L_1:
;delays.ppas,13 :: 		end;
$0754	$0008			RETURN
$073A	$	_delay_5500us:
;delays.ppas,41 :: 		begin
;delays.ppas,42 :: 		Delay_us(5500);
$073A	$3008			MOVLW	8
$073B	$1303			BCF	STATUS, RP1
$073C	$1283			BCF	STATUS, RP0
$073D	$00FB			MOVWF	STACK_11
$073E	$30FF			MOVLW	255
$073F	$00FA			MOVWF	STACK_10
$0740	$0BFB			DECFSZ	STACK_11, F
$0741	$2F43			GOTO	$+2
$0742	$2F46			GOTO	$+4
$0743	$0BFA			DECFSZ	STACK_10, F
$0744	$2F43			GOTO	$-1
$0745	$2F40			GOTO	$-5
$0746	$301E			MOVLW	30
$0747	$00FA			MOVWF	STACK_10
$0748	$0BFA			DECFSZ	STACK_10, F
$0749	$2F48			GOTO	$-1
$074A	$	delays_L_7:
;delays.ppas,43 :: 		end;
$074A	$0008			RETURN
$0903	$	_delay_50us:
;delays.ppas,26 :: 		begin
;delays.ppas,27 :: 		Delay_us(50);
$0903	$3010			MOVLW	16
$0904	$1303			BCF	STATUS, RP1
$0905	$1283			BCF	STATUS, RP0
$0906	$00FA			MOVWF	STACK_10
$0907	$0BFA			DECFSZ	STACK_10, F
$0908	$2907			GOTO	$-1
$0909	$0000			NOP
$090A	$	delays_L_4:
;delays.ppas,28 :: 		end;
$090A	$0008			RETURN
$0472	$	_lcd_cmd:
;lcd.ppas,19 :: 		
;lcd.ppas,20 :: 		
$0472	$1303			BCF	STATUS, RP1
$0473	$1283			BCF	STATUS, RP0
$0474	$0821			MOVF	lcd_ctrlport_address, 0
$0475	$0084			MOVWF	FSR
;lcd.ppas,22 :: 		
$0476	$0922			COMF	lcd____menable, W
$0477	$00F0			MOVWF	STACK_0
$0478	$0870			MOVF	STACK_0, 0
$0479	$0580			ANDWF	INDF, 1
;lcd.ppas,23 :: 		
$047A	$0923			COMF	lcd____mrs, W
$047B	$00F0			MOVWF	STACK_0
$047C	$0870			MOVF	STACK_0, 0
$047D	$0580			ANDWF	INDF, 1
;lcd.ppas,25 :: 		
$047E	$0824			MOVF	lcd_dataport_address, 0
$047F	$0084			MOVWF	FSR
;lcd.ppas,26 :: 		
$0480	$0826			MOVF	lcd____mdb6, 0
$0481	$0425			IORWF	lcd____mdb7, 0
$0482	$00F0			MOVWF	STACK_0
$0483	$0827			MOVF	lcd____mdb5, 0
$0484	$04F0			IORWF	STACK_0, 1
$0485	$0828			MOVF	lcd____mdb4, 0
$0486	$04F0			IORWF	STACK_0, 1
$0487	$09F0			COMF	STACK_0, F
$0488	$0870			MOVF	STACK_0, 0
$0489	$0580			ANDWF	INDF, 1
;lcd.ppas,28 :: 		
$048A	$3000			MOVLW	0
$048B	$1BD2			BTFSC	FARG_Lcd_Cmd, 7
$048C	$3001			MOVLW	1
$048D	$00F1			MOVWF	STACK_1
$048E	$0871			MOVF	STACK_1, 0
$048F	$3A01			XORLW	1
$0490	$1D03			BTFSS	STATUS, Z
$0491	$2C94			GOTO	lcd_L_2
$0492	$	lcd_L_1:
;lcd.ppas,29 :: 		
$0492	$0825			MOVF	lcd____mdb7, 0
$0493	$0480			IORWF	INDF, 1
$0494	$	lcd_L_2:
$0494	$	lcd_L_3:
;lcd.ppas,30 :: 		
$0494	$3000			MOVLW	0
$0495	$1B52			BTFSC	FARG_Lcd_Cmd, 6
$0496	$3001			MOVLW	1
$0497	$00F1			MOVWF	STACK_1
$0498	$0871			MOVF	STACK_1, 0
$0499	$3A01			XORLW	1
$049A	$1D03			BTFSS	STATUS, Z
$049B	$2C9E			GOTO	lcd_L_5
$049C	$	lcd_L_4:
;lcd.ppas,31 :: 		
$049C	$0826			MOVF	lcd____mdb6, 0
$049D	$0480			IORWF	INDF, 1
$049E	$	lcd_L_5:
$049E	$	lcd_L_6:
;lcd.ppas,32 :: 		
$049E	$3000			MOVLW	0
$049F	$1AD2			BTFSC	FARG_Lcd_Cmd, 5
$04A0	$3001			MOVLW	1
$04A1	$00F1			MOVWF	STACK_1
$04A2	$0871			MOVF	STACK_1, 0
$04A3	$3A01			XORLW	1
$04A4	$1D03			BTFSS	STATUS, Z
$04A5	$2CA8			GOTO	lcd_L_8
$04A6	$	lcd_L_7:
;lcd.ppas,33 :: 		
$04A6	$0827			MOVF	lcd____mdb5, 0
$04A7	$0480			IORWF	INDF, 1
$04A8	$	lcd_L_8:
$04A8	$	lcd_L_9:
;lcd.ppas,34 :: 		
$04A8	$3000			MOVLW	0
$04A9	$1A52			BTFSC	FARG_Lcd_Cmd, 4
$04AA	$3001			MOVLW	1
$04AB	$00F1			MOVWF	STACK_1
$04AC	$0871			MOVF	STACK_1, 0
$04AD	$3A01			XORLW	1
$04AE	$1D03			BTFSS	STATUS, Z
$04AF	$2CB2			GOTO	lcd_L_11
$04B0	$	lcd_L_10:
;lcd.ppas,35 :: 		
$04B0	$0828			MOVF	lcd____mdb4, 0
$04B1	$0480			IORWF	INDF, 1
$04B2	$	lcd_L_11:
$04B2	$	lcd_L_12:
;lcd.ppas,37 :: 		
$04B2	$0821			MOVF	lcd_ctrlport_address, 0
$04B3	$0084			MOVWF	FSR
;lcd.ppas,38 :: 		
$04B4	$0829			MOVF	lcd_lcdcmd_status, 0
$04B5	$3A01			XORLW	1
$04B6	$1D03			BTFSS	STATUS, Z
$04B7	$2CBD			GOTO	lcd_L_14
$04B8	$	lcd_L_13:
;lcd.ppas,39 :: 		
$04B8	$0923			COMF	lcd____mrs, W
$04B9	$00F0			MOVWF	STACK_0
$04BA	$0870			MOVF	STACK_0, 0
$04BB	$0580			ANDWF	INDF, 1
$04BC	$2CBF			GOTO	lcd_L_15
;lcd.ppas,40 :: 		
$04BD	$	lcd_L_14:
;lcd.ppas,41 :: 		
$04BD	$0823			MOVF	lcd____mrs, 0
$04BE	$0480			IORWF	INDF, 1
$04BF	$	lcd_L_15:
;lcd.ppas,43 :: 		
$04BF	$0822			MOVF	lcd____menable, 0
$04C0	$0480			IORWF	INDF, 1
;lcd.ppas,44 :: 		
$04C1	$2753			CALL	_delay_1us
;lcd.ppas,45 :: 		
$04C2	$0922			COMF	lcd____menable, W
$04C3	$00F0			MOVWF	STACK_0
$04C4	$0870			MOVF	STACK_0, 0
$04C5	$0580			ANDWF	INDF, 1
;lcd.ppas,47 :: 		
$04C6	$0923			COMF	lcd____mrs, W
$04C7	$00F0			MOVWF	STACK_0
$04C8	$0870			MOVF	STACK_0, 0
$04C9	$0580			ANDWF	INDF, 1
;lcd.ppas,49 :: 		
$04CA	$0824			MOVF	lcd_dataport_address, 0
$04CB	$0084			MOVWF	FSR
;lcd.ppas,50 :: 		
$04CC	$0826			MOVF	lcd____mdb6, 0
$04CD	$0425			IORWF	lcd____mdb7, 0
$04CE	$00F0			MOVWF	STACK_0
$04CF	$0827			MOVF	lcd____mdb5, 0
$04D0	$04F0			IORWF	STACK_0, 1
$04D1	$0828			MOVF	lcd____mdb4, 0
$04D2	$04F0			IORWF	STACK_0, 1
$04D3	$09F0			COMF	STACK_0, F
$04D4	$0870			MOVF	STACK_0, 0
$04D5	$0580			ANDWF	INDF, 1
;lcd.ppas,52 :: 		
$04D6	$3000			MOVLW	0
$04D7	$19D2			BTFSC	FARG_Lcd_Cmd, 3
$04D8	$3001			MOVLW	1
$04D9	$00F1			MOVWF	STACK_1
$04DA	$0871			MOVF	STACK_1, 0
$04DB	$3A01			XORLW	1
$04DC	$1D03			BTFSS	STATUS, Z
$04DD	$2CE0			GOTO	lcd_L_17
$04DE	$	lcd_L_16:
;lcd.ppas,53 :: 		
$04DE	$0825			MOVF	lcd____mdb7, 0
$04DF	$0480			IORWF	INDF, 1
$04E0	$	lcd_L_17:
$04E0	$	lcd_L_18:
;lcd.ppas,54 :: 		
$04E0	$3000			MOVLW	0
$04E1	$1952			BTFSC	FARG_Lcd_Cmd, 2
$04E2	$3001			MOVLW	1
$04E3	$00F1			MOVWF	STACK_1
$04E4	$0871			MOVF	STACK_1, 0
$04E5	$3A01			XORLW	1
$04E6	$1D03			BTFSS	STATUS, Z
$04E7	$2CEA			GOTO	lcd_L_20
$04E8	$	lcd_L_19:
;lcd.ppas,55 :: 		
$04E8	$0826			MOVF	lcd____mdb6, 0
$04E9	$0480			IORWF	INDF, 1
$04EA	$	lcd_L_20:
$04EA	$	lcd_L_21:
;lcd.ppas,56 :: 		
$04EA	$3000			MOVLW	0
$04EB	$18D2			BTFSC	FARG_Lcd_Cmd, 1
$04EC	$3001			MOVLW	1
$04ED	$00F1			MOVWF	STACK_1
$04EE	$0871			MOVF	STACK_1, 0
$04EF	$3A01			XORLW	1
$04F0	$1D03			BTFSS	STATUS, Z
$04F1	$2CF4			GOTO	lcd_L_23
$04F2	$	lcd_L_22:
;lcd.ppas,57 :: 		
$04F2	$0827			MOVF	lcd____mdb5, 0
$04F3	$0480			IORWF	INDF, 1
$04F4	$	lcd_L_23:
$04F4	$	lcd_L_24:
;lcd.ppas,58 :: 		
$04F4	$3001			MOVLW	1
$04F5	$0552			ANDWF	FARG_Lcd_Cmd, 0
$04F6	$00F1			MOVWF	STACK_1
$04F7	$0871			MOVF	STACK_1, 0
$04F8	$3A01			XORLW	1
$04F9	$1D03			BTFSS	STATUS, Z
$04FA	$2CFD			GOTO	lcd_L_26
$04FB	$	lcd_L_25:
;lcd.ppas,59 :: 		
$04FB	$0828			MOVF	lcd____mdb4, 0
$04FC	$0480			IORWF	INDF, 1
$04FD	$	lcd_L_26:
$04FD	$	lcd_L_27:
;lcd.ppas,61 :: 		
$04FD	$0821			MOVF	lcd_ctrlport_address, 0
$04FE	$0084			MOVWF	FSR
;lcd.ppas,62 :: 		
$04FF	$0829			MOVF	lcd_lcdcmd_status, 0
$0500	$3A01			XORLW	1
$0501	$1D03			BTFSS	STATUS, Z
$0502	$2D08			GOTO	lcd_L_29
$0503	$	lcd_L_28:
;lcd.ppas,63 :: 		
$0503	$0923			COMF	lcd____mrs, W
$0504	$00F0			MOVWF	STACK_0
$0505	$0870			MOVF	STACK_0, 0
$0506	$0580			ANDWF	INDF, 1
$0507	$2D0A			GOTO	lcd_L_30
;lcd.ppas,64 :: 		
$0508	$	lcd_L_29:
;lcd.ppas,65 :: 		
$0508	$0823			MOVF	lcd____mrs, 0
$0509	$0480			IORWF	INDF, 1
$050A	$	lcd_L_30:
;lcd.ppas,67 :: 		
$050A	$0822			MOVF	lcd____menable, 0
$050B	$0480			IORWF	INDF, 1
;lcd.ppas,68 :: 		
$050C	$2753			CALL	_delay_1us
;lcd.ppas,69 :: 		
$050D	$0922			COMF	lcd____menable, W
$050E	$00F0			MOVWF	STACK_0
$050F	$0870			MOVF	STACK_0, 0
$0510	$0580			ANDWF	INDF, 1
;lcd.ppas,71 :: 		
$0511	$0829			MOVF	lcd_lcdcmd_status, 0
$0512	$3A01			XORLW	1
$0513	$1D03			BTFSS	STATUS, Z
$0514	$2D17			GOTO	lcd_L_32
$0515	$	lcd_L_31:
;lcd.ppas,72 :: 		
$0515	$273A			CALL	_delay_5500us
$0516	$2D1A			GOTO	lcd_L_33
;lcd.ppas,73 :: 		
$0517	$	lcd_L_32:
;lcd.ppas,74 :: 		
$0517	$158A			BSF	PCLATH, 3
$0518	$2103			CALL	_delay_50us
$0519	$118A			BCF	PCLATH, 3
$051A	$	lcd_L_33:
$051A	$	lcd_L_0:
;lcd.ppas,75 :: 		
$051A	$0008			RETURN
$0251	$	_sdiv3232l:
$0251	$1303			BCF	STATUS, RP1
$0252	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0253	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0254	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0255	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0256	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0257	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$0258	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$0259	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$025A	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$025B	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$025C	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$025D	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$025E	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$025F	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0260	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0261	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0262	$3007			MOVLW	7
;math.ppas,559 :: 		
$0263	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0264	$	LOOPS3232A:
;math.ppas,561 :: 		
$0264	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0265	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0266	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0267	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$0268	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$0269	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$026A	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$026B	$2A7A			GOTO	SADD22LA
;math.ppas,570 :: 		
$026C	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$026D	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$026E	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$026F	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0270	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0271	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0272	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0273	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0274	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0275	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0276	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0277	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$0278	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$0279	$2A87			GOTO	SOK22LA
;math.ppas,585 :: 		
$027A	$	SADD22LA:
;math.ppas,586 :: 		
$027A	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$027B	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$027C	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$027D	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$027E	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$027F	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0280	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0281	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0282	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0283	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0284	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0285	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0286	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$0287	$	SOK22LA:
;math.ppas,602 :: 		
$0287	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$0288	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$0289	$2A64			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$028A	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$028B	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$028C	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$028D	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$028E	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$028F	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0290	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0291	$2AA0			GOTO	SADD22L8
;math.ppas,615 :: 		
$0292	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0293	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0294	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0295	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0296	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$0297	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$0298	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$0299	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$029A	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$029B	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$029C	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$029D	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$029E	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$029F	$2AAD			GOTO	SOK22L8
;math.ppas,630 :: 		
$02A0	$	SADD22L8:
;math.ppas,631 :: 		
$02A0	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$02A1	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$02A2	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$02A3	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$02A4	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$02A5	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$02A6	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$02A7	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$02A8	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$02A9	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$02AA	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$02AB	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$02AC	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$02AD	$	SOK22L8:
;math.ppas,647 :: 		
$02AD	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$02AE	$3007			MOVLW	7
;math.ppas,650 :: 		
$02AF	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$02B0	$	LOOPS3232B:
;math.ppas,652 :: 		
$02B0	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$02B1	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$02B2	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$02B3	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$02B4	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$02B5	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$02B6	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$02B7	$2AC6			GOTO	SADD22LB
;math.ppas,661 :: 		
$02B8	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$02B9	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$02BA	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$02BB	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$02BC	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$02BD	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$02BE	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$02BF	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$02C0	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$02C1	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$02C2	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$02C3	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$02C4	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$02C5	$2AD3			GOTO	SOK22LB
;math.ppas,676 :: 		
$02C6	$	SADD22LB:
;math.ppas,677 :: 		
$02C6	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$02C7	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$02C8	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$02C9	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$02CA	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$02CB	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$02CC	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$02CD	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$02CE	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$02CF	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$02D0	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$02D1	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$02D2	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$02D3	$	SOK22LB:
;math.ppas,693 :: 		
$02D3	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$02D4	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$02D5	$2AB0			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$02D6	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$02D7	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$02D8	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$02D9	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$02DA	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$02DB	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$02DC	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$02DD	$2AEC			GOTO	SADD22L16
;math.ppas,706 :: 		
$02DE	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$02DF	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$02E0	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$02E1	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$02E2	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$02E3	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$02E4	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$02E5	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$02E6	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$02E7	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$02E8	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$02E9	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$02EA	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$02EB	$2AF9			GOTO	SOK22L16
;math.ppas,721 :: 		
$02EC	$	SADD22L16:
;math.ppas,722 :: 		
$02EC	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$02ED	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$02EE	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$02EF	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$02F0	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$02F1	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$02F2	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$02F3	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$02F4	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$02F5	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$02F6	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$02F7	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$02F8	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$02F9	$	SOK22L16:
;math.ppas,738 :: 		
$02F9	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$02FA	$3007			MOVLW	7
;math.ppas,741 :: 		
$02FB	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$02FC	$	LOOPS3232C:
;math.ppas,743 :: 		
$02FC	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$02FD	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$02FE	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$02FF	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$0300	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$0301	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$0302	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$0303	$2B12			GOTO	SADD22LC
;math.ppas,752 :: 		
$0304	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$0305	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$0306	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$0307	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$0308	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$0309	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$030A	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$030B	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$030C	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$030D	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$030E	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$030F	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$0310	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$0311	$2B1F			GOTO	SOK22LC
;math.ppas,767 :: 		
$0312	$	SADD22LC:
;math.ppas,768 :: 		
$0312	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$0313	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$0314	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$0315	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$0316	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$0317	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$0318	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$0319	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$031A	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$031B	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$031C	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$031D	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$031E	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$031F	$	SOK22LC:
;math.ppas,784 :: 		
$031F	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$0320	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$0321	$2AFC			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$0322	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0323	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0324	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0325	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$0326	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$0327	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$0328	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$0329	$2B38			GOTO	SADD22L24
;math.ppas,797 :: 		
$032A	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$032B	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$032C	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$032D	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$032E	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$032F	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$0330	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0331	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0332	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0333	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0334	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0335	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0336	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0337	$2B45			GOTO	SOK22L24
;math.ppas,812 :: 		
$0338	$	SADD22L24:
;math.ppas,813 :: 		
$0338	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$0339	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$033A	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$033B	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$033C	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$033D	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$033E	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$033F	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$0340	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0341	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0342	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0343	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0344	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0345	$	SOK22L24:
;math.ppas,829 :: 		
$0345	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0346	$3007			MOVLW	7
;math.ppas,832 :: 		
$0347	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0348	$	LOOPS3232D:
;math.ppas,834 :: 		
$0348	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0349	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$034A	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$034B	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$034C	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$034D	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$034E	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$034F	$2B5E			GOTO	SADD22LD
;math.ppas,843 :: 		
$0350	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0351	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0352	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0353	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0354	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0355	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0356	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0357	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$0358	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$0359	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$035A	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$035B	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$035C	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$035D	$2B6B			GOTO	SOK22LD
;math.ppas,858 :: 		
$035E	$	SADD22LD:
;math.ppas,859 :: 		
$035E	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$035F	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0360	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0361	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0362	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0363	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0364	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0365	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0366	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0367	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$0368	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$0369	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$036A	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$036B	$	SOK22LD:
;math.ppas,876 :: 		
$036B	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$036C	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$036D	$2B48			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$036E	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$036F	$2B7E			GOTO	SOK22L
;math.ppas,882 :: 		
$0370	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0371	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0372	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0373	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0374	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0375	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0376	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0377	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$0378	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$0379	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$037A	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$037B	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$037C	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$037D	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$037E	$	SOK22L:
;math.ppas,897 :: 		
$037E	$	math_L_9:
;math.ppas,898 :: 		
$037E	$0008			RETURN
$08DA	$	_comfrem:
$08DA	$1303			BCF	STATUS, RP1
$08DB	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$08DC	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$08DD	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$08DE	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$08DF	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$08E0	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$08E1	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$08E2	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$08E3	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$08E4	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$08E5	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$08E6	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$08E7	$	math_L_10:
;math.ppas,915 :: 		
$08E7	$0008			RETURN
$08E8	$	_lcd_chr_cp:
;lcd.ppas,97 :: 		
;lcd.ppas,98 :: 		
$08E8	$1303			BCF	STATUS, RP1
$08E9	$1283			BCF	STATUS, RP0
$08EA	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,99 :: 		
$08EB	$0851			MOVF	FARG_Lcd_Chr_CP, 0
$08EC	$00D2			MOVWF	FARG_Lcd_Cmd
$08ED	$118A			BCF	PCLATH, 3
$08EE	$2472			CALL	_lcd_cmd
$08EF	$158A			BSF	PCLATH, 3
;lcd.ppas,100 :: 		
$08F0	$3001			MOVLW	1
$08F1	$00A9			MOVWF	lcd_lcdcmd_status
$08F2	$	lcd_L_48:
;lcd.ppas,101 :: 		
$08F2	$0008			RETURN
$08AF	$	_mul_16x16_u:
$08AF	$1303			BCF	STATUS, RP1
$08B0	$1283			BCF	STATUS, RP0
;math.ppas,42 :: 		
;math.ppas,44 :: 		
$08B1	$01FB			CLRF	STACK_11
;math.ppas,45 :: 		
$08B2	$01FA			CLRF	STACK_10
;math.ppas,46 :: 		
$08B3	$01F9			CLRF	STACK_9
;math.ppas,47 :: 		
$08B4	$3080			MOVLW	128
;math.ppas,48 :: 		
$08B5	$00F8			MOVWF	STACK_8
;math.ppas,49 :: 		
$08B6	$0CF1			RRF	STACK_1, F
;math.ppas,50 :: 		
$08B7	$0CF0			RRF	STACK_0, F
;math.ppas,51 :: 		
$08B8	$1C03			BTFSS	STATUS, C
;math.ppas,52 :: 		
$08B9	$28C3			GOTO	$+10
;math.ppas,53 :: 		
$08BA	$0874			MOVF	STACK_4, W
;math.ppas,54 :: 		
$08BB	$07F9			ADDWF	STACK_9, F
;math.ppas,55 :: 		
$08BC	$0875			MOVF	STACK_5, W
;math.ppas,56 :: 		
$08BD	$1803			BTFSC	STATUS, C
;math.ppas,57 :: 		
$08BE	$0F75			INCFSZ	STACK_5, W
;math.ppas,58 :: 		
$08BF	$07FA			ADDWF	STACK_10, F
;math.ppas,59 :: 		
$08C0	$1803			BTFSC	STATUS, C
;math.ppas,60 :: 		
$08C1	$0AFB			INCF	STACK_11, F
;math.ppas,61 :: 		
$08C2	$1003			BCF	STATUS, C
;math.ppas,62 :: 		
$08C3	$1FF0			BTFSS	STACK_0, 7
;math.ppas,63 :: 		
$08C4	$28CB			GOTO	$+7
;math.ppas,64 :: 		
$08C5	$0874			MOVF	STACK_4, W
;math.ppas,65 :: 		
$08C6	$07FA			ADDWF	STACK_10, F
;math.ppas,66 :: 		
$08C7	$0875			MOVF	STACK_5, W
;math.ppas,67 :: 		
$08C8	$1803			BTFSC	STATUS, C
;math.ppas,68 :: 		
$08C9	$0F75			INCFSZ	STACK_5, W
;math.ppas,69 :: 		
$08CA	$07FB			ADDWF	STACK_11, F
;math.ppas,70 :: 		
$08CB	$0CFB			RRF	STACK_11, F
;math.ppas,71 :: 		
$08CC	$0CFA			RRF	STACK_10, F
;math.ppas,72 :: 		
$08CD	$0CF9			RRF	STACK_9, F
;math.ppas,73 :: 		
$08CE	$0CF8			RRF	STACK_8, F
;math.ppas,74 :: 		
$08CF	$1C03			BTFSS	STATUS, C
;math.ppas,75 :: 		
$08D0	$28B6			GOTO	$-26
;math.ppas,76 :: 		
$08D1	$087B			MOVF	STACK_11, W
;math.ppas,77 :: 		
$08D2	$00F3			MOVWF	STACK_3
;math.ppas,78 :: 		
$08D3	$087A			MOVF	STACK_10, W
;math.ppas,79 :: 		
$08D4	$00F2			MOVWF	STACK_2
;math.ppas,80 :: 		
$08D5	$0879			MOVF	STACK_9, W
;math.ppas,81 :: 		
$08D6	$00F1			MOVWF	STACK_1
;math.ppas,82 :: 		
$08D7	$0878			MOVF	STACK_8, W
;math.ppas,83 :: 		
$08D8	$00F0			MOVWF	STACK_0
;math.ppas,84 :: 		
$08D9	$	math_L_1:
;math.ppas,85 :: 		
$08D9	$0008			RETURN
$0913	$	_delay_22us:
;delays.ppas,21 :: 		begin
;delays.ppas,22 :: 		Delay_us(22);
$0913	$3007			MOVLW	7
$0914	$1303			BCF	STATUS, RP1
$0915	$1283			BCF	STATUS, RP0
$0916	$00FA			MOVWF	STACK_10
$0917	$0BFA			DECFSZ	STACK_10, F
$0918	$2917			GOTO	$-1
$0919	$	delays_L_3:
;delays.ppas,23 :: 		end;
$0919	$0008			RETURN
$051B	$	_div_32x32_s:
$051B	$1303			BCF	STATUS, RP1
$051C	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$051D	$	FXD3232S:
;math.ppas,929 :: 		
$051D	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$051E	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$051F	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$0520	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$0521	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$0522	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$0523	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$0524	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$0525	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0526	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0527	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0528	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0529	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$052A	$2DAF			GOTO	END_ALL
;math.ppas,944 :: 		
$052B	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$052C	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$052D	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$052E	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$052F	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0530	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$0531	$2D3D			GOTO	CA3232S
;math.ppas,955 :: 		
$0532	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$0533	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$0534	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$0535	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0536	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0537	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0538	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0539	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$053A	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$053B	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$053C	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$053D	$	CA3232S:
;math.ppas,968 :: 		
$053D	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$053E	$2D4A			GOTO	C3232SX
;math.ppas,971 :: 		
$053F	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0540	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$0541	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$0542	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$0543	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$0544	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$0545	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$0546	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0547	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0548	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0549	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$054A	$	C3232SX:
;math.ppas,984 :: 		
$054A	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$054B	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$054C	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$054D	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$054E	$2D6B			GOTO	C3232SX1
;math.ppas,989 :: 		
$054F	$	C3232S:
;math.ppas,992 :: 		
$054F	$2251			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0550	$	C3232S2:
;math.ppas,996 :: 		
$0550	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$0551	$2D88			GOTO	C3232SX4
;math.ppas,998 :: 		
$0552	$	C3232SOK:
;math.ppas,999 :: 		
$0552	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$0553	$2DAF			GOTO	END_ALL
;math.ppas,1001 :: 		
$0554	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$0555	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$0556	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0557	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0558	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0559	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$055A	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$055B	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$055C	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$055D	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$055E	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$055F	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0560	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$0561	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$0562	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$0563	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$0564	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$0565	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$0566	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0567	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0568	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0569	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$056A	$2DAF			GOTO	END_ALL
;math.ppas,1026 :: 		
$056B	$	C3232SX1:
;math.ppas,1027 :: 		
$056B	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$056C	$2D82			GOTO	C3232SX3
;math.ppas,1029 :: 		
$056D	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$056E	$2D7C			GOTO	C3232SX2
;math.ppas,1031 :: 		
$056F	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0570	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$0571	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$0572	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$0573	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$0574	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$0575	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$0576	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0577	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0578	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0579	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$057A	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$057B	$2D52			GOTO	C3232SOK
;math.ppas,1044 :: 		
$057C	$	C3232SX2:
;math.ppas,1045 :: 		
$057C	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$057D	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$057E	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$057F	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0580	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$0581	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$0582	$	C3232SX3:
;math.ppas,1053 :: 		
$0582	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$0583	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$0584	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$0585	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$0586	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0587	$2D4F			GOTO	C3232S
;math.ppas,1061 :: 		
$0588	$	C3232SX4:
;math.ppas,1062 :: 		
$0588	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0589	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$058A	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$058B	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$058C	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$058D	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$058E	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$058F	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0590	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$0591	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$0592	$2D52			GOTO	C3232SOK
;math.ppas,1073 :: 		
$0593	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$0594	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$0595	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$0596	$2D52			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0597	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0598	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0599	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$059A	$2D52			GOTO	C3232SOK
;math.ppas,1081 :: 		
$059B	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$059C	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$059D	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$059E	$2D52			GOTO	C3232SOK
;math.ppas,1085 :: 		
$059F	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$05A0	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$05A1	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$05A2	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$05A3	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$05A4	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$05A5	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$05A6	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$05A7	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$05A8	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$05A9	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$05AA	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$05AB	$2D52			GOTO	C3232SOK
;math.ppas,1098 :: 		
$05AC	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$05AD	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$05AE	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$05AF	$	END_ALL:
;math.ppas,1102 :: 		
$05AF	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$05B0	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$05B1	$2DB5			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$05B2	$158A			BSF	PCLATH, 3
$05B3	$20DA			CALL	_comfrem
$05B4	$118A			BCF	PCLATH, 3
;math.ppas,1108 :: 		
$05B5	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$05B5	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$05B6	$	math_L_11:
;math.ppas,1111 :: 		
$05B6	$0008			RETURN
$0882	$	_div_16x16_s_l:
$0882	$1303			BCF	STATUS, RP1
$0883	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$0884	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$0885	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$0886	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$0887	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$0888	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$0889	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$088A	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$088B	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$088C	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$088D	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$088E	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$088F	$300F			MOVLW	15
;math.ppas,307 :: 		
$0890	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$0891	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$0892	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$0893	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$0894	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$0895	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$0896	$289D			GOTO	$+7
;math.ppas,315 :: 		
$0897	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$0898	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$0899	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$089A	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$089B	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$089C	$28A2			GOTO	$+6
;math.ppas,322 :: 		
$089D	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$089E	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$089F	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$08A0	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$08A1	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$08A2	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$08A3	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$08A4	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$08A5	$2891			GOTO	$-20
;math.ppas,334 :: 		
$08A6	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$08A7	$28AE			GOTO	$+7
;math.ppas,336 :: 		
$08A8	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$08A9	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$08AA	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$08AB	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$08AC	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$08AD	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$08AE	$	math_L_6:
;math.ppas,343 :: 		
$08AE	$0008			RETURN
$0132	$	_lcd_config:
;lcd.ppas,115 :: 		
;lcd.ppas,116 :: 		
$0132	$273A			CALL	_delay_5500us
;lcd.ppas,117 :: 		
$0133	$273A			CALL	_delay_5500us
;lcd.ppas,118 :: 		
$0134	$273A			CALL	_delay_5500us
;lcd.ppas,120 :: 		
$0135	$0847			MOVF	FARG_Lcd_Config+1, 0
$0136	$00F0			MOVWF	STACK_0
$0137	$3001			MOVLW	1
$0138	$00F4			MOVWF	STACK_4
$0139	$0870			MOVF	STACK_0, 0
$013A	$	L_Lcd_Config_0:
$013A	$1903			BTFSC	STATUS, Z
$013B	$2940			GOTO	L_Lcd_Config_1
$013C	$0DF4			RLF	STACK_4, 1
$013D	$1074			BCF	STACK_4, 0
$013E	$3FFF			ADDLW	255
$013F	$293A			GOTO	L_Lcd_Config_0
$0140	$	L_Lcd_Config_1:
$0140	$0874			MOVF	STACK_4, 0
$0141	$00A5			MOVWF	lcd____mdb7
;lcd.ppas,121 :: 		
$0142	$0848			MOVF	FARG_Lcd_Config+2, 0
$0143	$00F0			MOVWF	STACK_0
$0144	$3001			MOVLW	1
$0145	$00F3			MOVWF	STACK_3
$0146	$0870			MOVF	STACK_0, 0
$0147	$	L_Lcd_Config_2:
$0147	$1903			BTFSC	STATUS, Z
$0148	$294D			GOTO	L_Lcd_Config_3
$0149	$0DF3			RLF	STACK_3, 1
$014A	$1073			BCF	STACK_3, 0
$014B	$3FFF			ADDLW	255
$014C	$2947			GOTO	L_Lcd_Config_2
$014D	$	L_Lcd_Config_3:
$014D	$0873			MOVF	STACK_3, 0
$014E	$00A6			MOVWF	lcd____mdb6
;lcd.ppas,122 :: 		
$014F	$0849			MOVF	FARG_Lcd_Config+3, 0
$0150	$00F0			MOVWF	STACK_0
$0151	$3001			MOVLW	1
$0152	$00F2			MOVWF	STACK_2
$0153	$0870			MOVF	STACK_0, 0
$0154	$	L_Lcd_Config_4:
$0154	$1903			BTFSC	STATUS, Z
$0155	$295A			GOTO	L_Lcd_Config_5
$0156	$0DF2			RLF	STACK_2, 1
$0157	$1072			BCF	STACK_2, 0
$0158	$3FFF			ADDLW	255
$0159	$2954			GOTO	L_Lcd_Config_4
$015A	$	L_Lcd_Config_5:
$015A	$0872			MOVF	STACK_2, 0
$015B	$00A7			MOVWF	lcd____mdb5
;lcd.ppas,123 :: 		
$015C	$084A			MOVF	FARG_Lcd_Config+4, 0
$015D	$00F0			MOVWF	STACK_0
$015E	$3001			MOVLW	1
$015F	$00F1			MOVWF	STACK_1
$0160	$0870			MOVF	STACK_0, 0
$0161	$	L_Lcd_Config_6:
$0161	$1903			BTFSC	STATUS, Z
$0162	$2967			GOTO	L_Lcd_Config_7
$0163	$0DF1			RLF	STACK_1, 1
$0164	$1071			BCF	STACK_1, 0
$0165	$3FFF			ADDLW	255
$0166	$2961			GOTO	L_Lcd_Config_6
$0167	$	L_Lcd_Config_7:
$0167	$0871			MOVF	STACK_1, 0
$0168	$00A8			MOVWF	lcd____mdb4
;lcd.ppas,124 :: 		
$0169	$084C			MOVF	FARG_Lcd_Config+6, 0
$016A	$00F0			MOVWF	STACK_0
$016B	$3001			MOVLW	1
$016C	$00A3			MOVWF	lcd____mrs
$016D	$0870			MOVF	STACK_0, 0
$016E	$	L_Lcd_Config_8:
$016E	$1903			BTFSC	STATUS, Z
$016F	$2974			GOTO	L_Lcd_Config_9
$0170	$0DA3			RLF	lcd____mrs, 1
$0171	$1023			BCF	lcd____mrs, 0
$0172	$3FFF			ADDLW	255
$0173	$296E			GOTO	L_Lcd_Config_8
$0174	$	L_Lcd_Config_9:
;lcd.ppas,125 :: 		
$0174	$084D			MOVF	FARG_Lcd_Config+7, 0
$0175	$00F0			MOVWF	STACK_0
$0176	$3001			MOVLW	1
$0177	$00AA			MOVWF	lcd____mrw
$0178	$0870			MOVF	STACK_0, 0
$0179	$	L_Lcd_Config_10:
$0179	$1903			BTFSC	STATUS, Z
$017A	$297F			GOTO	L_Lcd_Config_11
$017B	$0DAA			RLF	lcd____mrw, 1
$017C	$102A			BCF	lcd____mrw, 0
$017D	$3FFF			ADDLW	255
$017E	$2979			GOTO	L_Lcd_Config_10
$017F	$	L_Lcd_Config_11:
;lcd.ppas,126 :: 		
$017F	$084E			MOVF	FARG_Lcd_Config+8, 0
$0180	$00F0			MOVWF	STACK_0
$0181	$3001			MOVLW	1
$0182	$00A2			MOVWF	lcd____menable
$0183	$0870			MOVF	STACK_0, 0
$0184	$	L_Lcd_Config_12:
$0184	$1903			BTFSC	STATUS, Z
$0185	$298A			GOTO	L_Lcd_Config_13
$0186	$0DA2			RLF	lcd____menable, 1
$0187	$1022			BCF	lcd____menable, 0
$0188	$3FFF			ADDLW	255
$0189	$2984			GOTO	L_Lcd_Config_12
$018A	$	L_Lcd_Config_13:
;lcd.ppas,128 :: 		
$018A	$0846			MOVF	FARG_Lcd_Config, 0
$018B	$00A4			MOVWF	lcd_dataport_address
;lcd.ppas,129 :: 		
$018C	$084B			MOVF	FARG_Lcd_Config+5, 0
$018D	$00A1			MOVWF	lcd_ctrlport_address
;lcd.ppas,131 :: 		
$018E	$0846			MOVF	FARG_Lcd_Config, 0
$018F	$0084			MOVWF	FSR
;lcd.ppas,133 :: 		
$0190	$0873			MOVF	STACK_3, 0
$0191	$0474			IORWF	STACK_4, 0
$0192	$00F0			MOVWF	STACK_0
$0193	$0872			MOVF	STACK_2, 0
$0194	$04F0			IORWF	STACK_0, 1
$0195	$0871			MOVF	STACK_1, 0
$0196	$04F0			IORWF	STACK_0, 1
$0197	$09F0			COMF	STACK_0, F
$0198	$0870			MOVF	STACK_0, 0
$0199	$0580			ANDWF	INDF, 1
;lcd.ppas,134 :: 		
$019A	$	lcd_L_56:
$019A	$1784			BSF	FSR, 7
$019B	$	lcd_L_57:
;lcd.ppas,135 :: 		
$019B	$0826			MOVF	lcd____mdb6, 0
$019C	$0425			IORWF	lcd____mdb7, 0
$019D	$00F0			MOVWF	STACK_0
$019E	$0827			MOVF	lcd____mdb5, 0
$019F	$04F0			IORWF	STACK_0, 1
$01A0	$0828			MOVF	lcd____mdb4, 0
$01A1	$04F0			IORWF	STACK_0, 1
$01A2	$09F0			COMF	STACK_0, F
$01A3	$0870			MOVF	STACK_0, 0
$01A4	$0580			ANDWF	INDF, 1
;lcd.ppas,136 :: 		
$01A5	$1384			BCF	FSR, 7
$01A6	$	lcd_L_59:
;lcd.ppas,139 :: 		
$01A6	$0821			MOVF	lcd_ctrlport_address, 0
$01A7	$0084			MOVWF	FSR
;lcd.ppas,141 :: 		
$01A8	$082A			MOVF	lcd____mrw, 0
$01A9	$0423			IORWF	lcd____mrs, 0
$01AA	$00F0			MOVWF	STACK_0
$01AB	$0822			MOVF	lcd____menable, 0
$01AC	$04F0			IORWF	STACK_0, 1
$01AD	$09F0			COMF	STACK_0, F
$01AE	$0870			MOVF	STACK_0, 0
$01AF	$0580			ANDWF	INDF, 1
;lcd.ppas,142 :: 		
$01B0	$	lcd_L_60:
$01B0	$1784			BSF	FSR, 7
$01B1	$	lcd_L_61:
;lcd.ppas,143 :: 		
$01B1	$082A			MOVF	lcd____mrw, 0
$01B2	$0423			IORWF	lcd____mrs, 0
$01B3	$00F0			MOVWF	STACK_0
$01B4	$0822			MOVF	lcd____menable, 0
$01B5	$04F0			IORWF	STACK_0, 1
$01B6	$09F0			COMF	STACK_0, F
$01B7	$0870			MOVF	STACK_0, 0
$01B8	$0580			ANDWF	INDF, 1
;lcd.ppas,144 :: 		
$01B9	$1384			BCF	FSR, 7
$01BA	$	lcd_L_63:
;lcd.ppas,148 :: 		
$01BA	$0824			MOVF	lcd_dataport_address, 0
$01BB	$0084			MOVWF	FSR
;lcd.ppas,149 :: 		
$01BC	$0827			MOVF	lcd____mdb5, 0
$01BD	$0400			IORWF	INDF, 0
$01BE	$00F0			MOVWF	STACK_0
$01BF	$0828			MOVF	lcd____mdb4, 0
$01C0	$0470			IORWF	STACK_0, 0
$01C1	$0080			MOVWF	INDF
;lcd.ppas,151 :: 		
$01C2	$0821			MOVF	lcd_ctrlport_address, 0
$01C3	$0084			MOVWF	FSR
;lcd.ppas,152 :: 		
$01C4	$0822			MOVF	lcd____menable, 0
$01C5	$0480			IORWF	INDF, 1
;lcd.ppas,153 :: 		
$01C6	$0922			COMF	lcd____menable, W
$01C7	$00F0			MOVWF	STACK_0
$01C8	$0870			MOVF	STACK_0, 0
$01C9	$0580			ANDWF	INDF, 1
;lcd.ppas,155 :: 		
$01CA	$273A			CALL	_delay_5500us
;lcd.ppas,160 :: 		
$01CB	$0822			MOVF	lcd____menable, 0
$01CC	$0480			IORWF	INDF, 1
;lcd.ppas,161 :: 		
$01CD	$0922			COMF	lcd____menable, W
$01CE	$00F0			MOVWF	STACK_0
$01CF	$0870			MOVF	STACK_0, 0
$01D0	$0580			ANDWF	INDF, 1
;lcd.ppas,163 :: 		
$01D1	$273A			CALL	_delay_5500us
;lcd.ppas,168 :: 		
$01D2	$0822			MOVF	lcd____menable, 0
$01D3	$0480			IORWF	INDF, 1
;lcd.ppas,169 :: 		
$01D4	$0922			COMF	lcd____menable, W
$01D5	$00F0			MOVWF	STACK_0
$01D6	$0870			MOVF	STACK_0, 0
$01D7	$0580			ANDWF	INDF, 1
;lcd.ppas,171 :: 		
$01D8	$273A			CALL	_delay_5500us
;lcd.ppas,174 :: 		
$01D9	$0824			MOVF	lcd_dataport_address, 0
$01DA	$0084			MOVWF	FSR
;lcd.ppas,175 :: 		
$01DB	$0827			MOVF	lcd____mdb5, 0
$01DC	$0480			IORWF	INDF, 1
;lcd.ppas,176 :: 		
$01DD	$0928			COMF	lcd____mdb4, W
$01DE	$00F0			MOVWF	STACK_0
$01DF	$0870			MOVF	STACK_0, 0
$01E0	$0580			ANDWF	INDF, 1
;lcd.ppas,178 :: 		
$01E1	$0821			MOVF	lcd_ctrlport_address, 0
$01E2	$0084			MOVWF	FSR
;lcd.ppas,179 :: 		
$01E3	$0822			MOVF	lcd____menable, 0
$01E4	$0480			IORWF	INDF, 1
;lcd.ppas,180 :: 		
$01E5	$0922			COMF	lcd____menable, W
$01E6	$00F0			MOVWF	STACK_0
$01E7	$0870			MOVF	STACK_0, 0
$01E8	$0580			ANDWF	INDF, 1
;lcd.ppas,182 :: 		
$01E9	$273A			CALL	_delay_5500us
;lcd.ppas,187 :: 		
$01EA	$0822			MOVF	lcd____menable, 0
$01EB	$0480			IORWF	INDF, 1
;lcd.ppas,188 :: 		
$01EC	$0922			COMF	lcd____menable, W
$01ED	$00F1			MOVWF	STACK_1
$01EE	$0871			MOVF	STACK_1, 0
$01EF	$0580			ANDWF	INDF, 1
;lcd.ppas,190 :: 		
$01F0	$0824			MOVF	lcd_dataport_address, 0
$01F1	$0084			MOVWF	FSR
;lcd.ppas,191 :: 		
$01F2	$0927			COMF	lcd____mdb5, W
$01F3	$00F0			MOVWF	STACK_0
$01F4	$0870			MOVF	STACK_0, 0
$01F5	$0580			ANDWF	INDF, 1
;lcd.ppas,192 :: 		
$01F6	$0825			MOVF	lcd____mdb7, 0
$01F7	$0480			IORWF	INDF, 1
;lcd.ppas,194 :: 		
$01F8	$0821			MOVF	lcd_ctrlport_address, 0
$01F9	$0084			MOVWF	FSR
;lcd.ppas,195 :: 		
$01FA	$0822			MOVF	lcd____menable, 0
$01FB	$0480			IORWF	INDF, 1
;lcd.ppas,196 :: 		
$01FC	$0871			MOVF	STACK_1, 0
$01FD	$0580			ANDWF	INDF, 1
;lcd.ppas,198 :: 		
$01FE	$273A			CALL	_delay_5500us
;lcd.ppas,201 :: 		
$01FF	$0824			MOVF	lcd_dataport_address, 0
$0200	$0084			MOVWF	FSR
;lcd.ppas,202 :: 		
$0201	$0925			COMF	lcd____mdb7, W
$0202	$00F0			MOVWF	STACK_0
$0203	$0870			MOVF	STACK_0, 0
$0204	$0580			ANDWF	INDF, 1
;lcd.ppas,203 :: 		
$0205	$0828			MOVF	lcd____mdb4, 0
$0206	$0480			IORWF	INDF, 1
;lcd.ppas,204 :: 		
$0207	$0821			MOVF	lcd_ctrlport_address, 0
$0208	$0084			MOVWF	FSR
;lcd.ppas,205 :: 		
$0209	$0822			MOVF	lcd____menable, 0
$020A	$0480			IORWF	INDF, 1
;lcd.ppas,206 :: 		
$020B	$0922			COMF	lcd____menable, W
$020C	$00F1			MOVWF	STACK_1
$020D	$0871			MOVF	STACK_1, 0
$020E	$0580			ANDWF	INDF, 1
;lcd.ppas,207 :: 		
$020F	$0824			MOVF	lcd_dataport_address, 0
$0210	$0084			MOVWF	FSR
;lcd.ppas,208 :: 		
$0211	$0928			COMF	lcd____mdb4, W
$0212	$00F0			MOVWF	STACK_0
$0213	$0870			MOVF	STACK_0, 0
$0214	$0580			ANDWF	INDF, 1
;lcd.ppas,209 :: 		
$0215	$0821			MOVF	lcd_ctrlport_address, 0
$0216	$0084			MOVWF	FSR
;lcd.ppas,210 :: 		
$0217	$0822			MOVF	lcd____menable, 0
$0218	$0480			IORWF	INDF, 1
;lcd.ppas,211 :: 		
$0219	$0871			MOVF	STACK_1, 0
$021A	$0580			ANDWF	INDF, 1
;lcd.ppas,213 :: 		
$021B	$273A			CALL	_delay_5500us
;lcd.ppas,218 :: 		
$021C	$0822			MOVF	lcd____menable, 0
$021D	$0480			IORWF	INDF, 1
;lcd.ppas,219 :: 		
$021E	$0922			COMF	lcd____menable, W
$021F	$00F0			MOVWF	STACK_0
$0220	$0870			MOVF	STACK_0, 0
$0221	$0580			ANDWF	INDF, 1
;lcd.ppas,220 :: 		
$0222	$0824			MOVF	lcd_dataport_address, 0
$0223	$0084			MOVWF	FSR
;lcd.ppas,221 :: 		
$0224	$0828			MOVF	lcd____mdb4, 0
$0225	$0480			IORWF	INDF, 1
;lcd.ppas,222 :: 		
$0226	$0821			MOVF	lcd_ctrlport_address, 0
$0227	$0084			MOVWF	FSR
;lcd.ppas,223 :: 		
$0228	$0822			MOVF	lcd____menable, 0
$0229	$0480			IORWF	INDF, 1
;lcd.ppas,224 :: 		
$022A	$0870			MOVF	STACK_0, 0
$022B	$0580			ANDWF	INDF, 1
;lcd.ppas,226 :: 		
$022C	$273A			CALL	_delay_5500us
;lcd.ppas,229 :: 		
$022D	$0824			MOVF	lcd_dataport_address, 0
$022E	$0084			MOVWF	FSR
;lcd.ppas,230 :: 		
$022F	$0928			COMF	lcd____mdb4, W
$0230	$00F0			MOVWF	STACK_0
$0231	$0870			MOVF	STACK_0, 0
$0232	$0580			ANDWF	INDF, 1
;lcd.ppas,231 :: 		
$0233	$0821			MOVF	lcd_ctrlport_address, 0
$0234	$0084			MOVWF	FSR
;lcd.ppas,232 :: 		
$0235	$0822			MOVF	lcd____menable, 0
$0236	$0480			IORWF	INDF, 1
;lcd.ppas,233 :: 		
$0237	$0922			COMF	lcd____menable, W
$0238	$00F1			MOVWF	STACK_1
$0239	$0871			MOVF	STACK_1, 0
$023A	$0580			ANDWF	INDF, 1
;lcd.ppas,234 :: 		
$023B	$0824			MOVF	lcd_dataport_address, 0
$023C	$0084			MOVWF	FSR
;lcd.ppas,235 :: 		
$023D	$0828			MOVF	lcd____mdb4, 0
$023E	$0400			IORWF	INDF, 0
$023F	$00F0			MOVWF	STACK_0
$0240	$0827			MOVF	lcd____mdb5, 0
$0241	$04F0			IORWF	STACK_0, 1
$0242	$0826			MOVF	lcd____mdb6, 0
$0243	$04F0			IORWF	STACK_0, 1
$0244	$0825			MOVF	lcd____mdb7, 0
$0245	$0470			IORWF	STACK_0, 0
$0246	$0080			MOVWF	INDF
;lcd.ppas,236 :: 		
$0247	$0821			MOVF	lcd_ctrlport_address, 0
$0248	$0084			MOVWF	FSR
;lcd.ppas,237 :: 		
$0249	$0822			MOVF	lcd____menable, 0
$024A	$0480			IORWF	INDF, 1
;lcd.ppas,238 :: 		
$024B	$0871			MOVF	STACK_1, 0
$024C	$0580			ANDWF	INDF, 1
;lcd.ppas,240 :: 		
$024D	$273A			CALL	_delay_5500us
;lcd.ppas,242 :: 		
$024E	$3001			MOVLW	1
$024F	$00A9			MOVWF	lcd_lcdcmd_status
$0250	$	lcd_L_55:
;lcd.ppas,243 :: 		
$0250	$0008			RETURN
$0800	$	_lcd_out:
;lcd.ppas,252 :: 		
;lcd.ppas,254 :: 		
$0800	$	lcd_L_68:
$0800	$1303			BCF	STATUS, RP1
$0801	$1283			BCF	STATUS, RP0
$0802	$0846			MOVF	FARG_Lcd_Out, 0
$0803	$3A01			XORLW	1
$0804	$1D03			BTFSS	STATUS, Z
$0805	$2809			GOTO	lcd_L_69
$0806	$	lcd_L_67:
$0806	$3080			MOVLW	128
$0807	$00C6			MOVWF	FARG_Lcd_Out
$0808	$2820			GOTO	lcd_L_66
$0809	$	lcd_L_69:
;lcd.ppas,255 :: 		
$0809	$	lcd_L_71:
$0809	$0846			MOVF	FARG_Lcd_Out, 0
$080A	$3A02			XORLW	2
$080B	$1D03			BTFSS	STATUS, Z
$080C	$2810			GOTO	lcd_L_72
$080D	$	lcd_L_70:
$080D	$30C0			MOVLW	192
$080E	$00C6			MOVWF	FARG_Lcd_Out
$080F	$2820			GOTO	lcd_L_66
$0810	$	lcd_L_72:
;lcd.ppas,256 :: 		
$0810	$	lcd_L_74:
$0810	$0846			MOVF	FARG_Lcd_Out, 0
$0811	$3A03			XORLW	3
$0812	$1D03			BTFSS	STATUS, Z
$0813	$2817			GOTO	lcd_L_75
$0814	$	lcd_L_73:
$0814	$3094			MOVLW	148
$0815	$00C6			MOVWF	FARG_Lcd_Out
$0816	$2820			GOTO	lcd_L_66
$0817	$	lcd_L_75:
;lcd.ppas,257 :: 		
$0817	$	lcd_L_77:
$0817	$0846			MOVF	FARG_Lcd_Out, 0
$0818	$3A04			XORLW	4
$0819	$1D03			BTFSS	STATUS, Z
$081A	$281E			GOTO	lcd_L_78
$081B	$	lcd_L_76:
$081B	$30D4			MOVLW	212
$081C	$00C6			MOVWF	FARG_Lcd_Out
;lcd.ppas,258 :: 		
$081D	$2820			GOTO	lcd_L_66
$081E	$	lcd_L_78:
$081E	$3080			MOVLW	128
$081F	$00C6			MOVWF	FARG_Lcd_Out
$0820	$	lcd_L_66:
;lcd.ppas,260 :: 		
$0820	$0347			DECF	FARG_Lcd_Out+1, 0
$0821	$00F0			MOVWF	STACK_0
$0822	$0846			MOVF	FARG_Lcd_Out, 0
$0823	$07F0			ADDWF	STACK_0, 1
$0824	$0870			MOVF	STACK_0, 0
$0825	$00C6			MOVWF	FARG_Lcd_Out
;lcd.ppas,261 :: 		
$0826	$0870			MOVF	STACK_0, 0
$0827	$00D2			MOVWF	FARG_Lcd_Cmd
$0828	$118A			BCF	PCLATH, 3
$0829	$2472			CALL	_lcd_cmd
$082A	$158A			BSF	PCLATH, 3
;lcd.ppas,262 :: 		
$082B	$01A9			CLRF	lcd_lcdcmd_status, 1
;lcd.ppas,263 :: 		
$082C	$01C9			CLRF	_lcd_out_local_i, 1
;lcd.ppas,264 :: 		
$082D	$	lcd_L_80:
$082D	$0849			MOVF	_lcd_out_local_i, 0
$082E	$0748			ADDWF	FARG_Lcd_Out+2, 0
$082F	$0084			MOVWF	FSR
$0830	$0800			MOVF	INDF, 0
$0831	$00F2			MOVWF	STACK_2
$0832	$0872			MOVF	STACK_2, 0
$0833	$3A00			XORLW	0
$0834	$1903			BTFSC	STATUS, Z
$0835	$283E			GOTO	lcd_L_81
;lcd.ppas,266 :: 		
$0836	$0849			MOVF	_lcd_out_local_i, 0
$0837	$0748			ADDWF	FARG_Lcd_Out+2, 0
$0838	$0084			MOVWF	FSR
$0839	$0800			MOVF	INDF, 0
$083A	$00D1			MOVWF	FARG_Lcd_Chr_CP
$083B	$20E8			CALL	_lcd_chr_cp
;lcd.ppas,267 :: 		
$083C	$0AC9			INCF	_lcd_out_local_i, 1
;lcd.ppas,268 :: 		
$083D	$282D			GOTO	lcd_L_80
$083E	$	lcd_L_81:
;lcd.ppas,269 :: 		
$083E	$3001			MOVLW	1
$083F	$00A9			MOVWF	lcd_lcdcmd_status
$0840	$	lcd_L_65:
;lcd.ppas,270 :: 		
$0840	$0008			RETURN
$065D	$	_pwm1_change_duty:
;PWM_c21.ppas,53 :: 		
;PWM_c21.ppas,54 :: 		
$065D	$1303			BCF	STATUS, RP1
$065E	$1683			BSF	STATUS, RP0
$065F	$0812			MOVF	PR2, 0
$0660	$00F0			MOVWF	STACK_0
$0661	$01F1			CLRF	STACK_0+1
$0662	$0870			MOVF	STACK_0, 0
$0663	$3F01			ADDLW	1
$0664	$00F4			MOVWF	STACK_4
$0665	$3000			MOVLW	0
$0666	$1803			BTFSC	STATUS, C
$0667	$3F01			ADDLW	1
$0668	$0771			ADDWF	STACK_0+1, 0
$0669	$00F5			MOVWF	STACK_4+1
$066A	$1283			BCF	STATUS, RP0
$066B	$0846			MOVF	FARG_PWM1_Change_Duty, 0
$066C	$00F0			MOVWF	STACK_0
$066D	$01F1			CLRF	STACK_0+1
$066E	$158A			BSF	PCLATH, 3
$066F	$20AF			CALL	_mul_16x16_u
$0670	$118A			BCF	PCLATH, 3
$0671	$3006			MOVLW	6
$0672	$00F2			MOVWF	STACK_2
$0673	$0870			MOVF	STACK_0, 0
$0674	$00F8			MOVWF	STACK_8
$0675	$0871			MOVF	STACK_0+1, 0
$0676	$00F9			MOVWF	STACK_8+1
$0677	$0872			MOVF	STACK_2, 0
$0678	$	L_PWM1_Change_Duty_2:
$0678	$1903			BTFSC	STATUS, Z
$0679	$2E7F			GOTO	L_PWM1_Change_Duty_3
$067A	$0CF9			RRF	STACK_8+1, 1
$067B	$0CF8			RRF	STACK_8, 1
$067C	$13F9			BCF	STACK_8+1, 7
$067D	$3FFF			ADDLW	255
$067E	$2E78			GOTO	L_PWM1_Change_Duty_2
$067F	$	L_PWM1_Change_Duty_3:
;PWM_c21.ppas,55 :: 		
$067F	$0878			MOVF	STACK_8, 0
$0680	$00F0			MOVWF	STACK_0
$0681	$0879			MOVF	STACK_8+1, 0
$0682	$00F1			MOVWF	STACK_0+1
$0683	$0DF0			RLF	STACK_0, 1
$0684	$0DF1			RLF	STACK_0+1, 1
$0685	$1070			BCF	STACK_0, 0
$0686	$0DF0			RLF	STACK_0, 1
$0687	$0DF1			RLF	STACK_0+1, 1
$0688	$1070			BCF	STACK_0, 0
$0689	$0DF0			RLF	STACK_0, 1
$068A	$0DF1			RLF	STACK_0+1, 1
$068B	$1070			BCF	STACK_0, 0
$068C	$0DF0			RLF	STACK_0, 1
$068D	$0DF1			RLF	STACK_0+1, 1
$068E	$1070			BCF	STACK_0, 0
$068F	$3030			MOVLW	48
$0690	$0570			ANDWF	STACK_0, 0
$0691	$00F6			MOVWF	STACK_6
$0692	$0871			MOVF	STACK_0+1, 0
$0693	$00F7			MOVWF	STACK_6+1
$0694	$3000			MOVLW	0
$0695	$05F7			ANDWF	STACK_6+1, 1
;PWM_c21.ppas,56 :: 		
$0696	$0878			MOVF	STACK_8, 0
$0697	$00F0			MOVWF	STACK_0
$0698	$0879			MOVF	STACK_8+1, 0
$0699	$00F1			MOVWF	STACK_0+1
$069A	$0CF1			RRF	STACK_0+1, 1
$069B	$0CF0			RRF	STACK_0, 1
$069C	$13F1			BCF	STACK_0+1, 7
$069D	$0CF1			RRF	STACK_0+1, 1
$069E	$0CF0			RRF	STACK_0, 1
$069F	$13F1			BCF	STACK_0+1, 7
$06A0	$0870			MOVF	STACK_0, 0
$06A1	$0095			MOVWF	CCPR1L
;PWM_c21.ppas,57 :: 		
$06A2	$300F			MOVLW	15
$06A3	$0597			ANDWF	CCP1CON, 1
;PWM_c21.ppas,58 :: 		
$06A4	$0876			MOVF	STACK_6, 0
$06A5	$0497			IORWF	CCP1CON, 1
$06A6	$	PWM_c21_L_7:
;PWM_c21.ppas,59 :: 		
$06A6	$0008			RETURN
$0613	$	_pwm2_change_duty:
;PWM_c21.ppas,88 :: 		
;PWM_c21.ppas,89 :: 		
$0613	$1303			BCF	STATUS, RP1
$0614	$1683			BSF	STATUS, RP0
$0615	$0812			MOVF	PR2, 0
$0616	$00F0			MOVWF	STACK_0
$0617	$01F1			CLRF	STACK_0+1
$0618	$0870			MOVF	STACK_0, 0
$0619	$3F01			ADDLW	1
$061A	$00F4			MOVWF	STACK_4
$061B	$3000			MOVLW	0
$061C	$1803			BTFSC	STATUS, C
$061D	$3F01			ADDLW	1
$061E	$0771			ADDWF	STACK_0+1, 0
$061F	$00F5			MOVWF	STACK_4+1
$0620	$1283			BCF	STATUS, RP0
$0621	$0846			MOVF	FARG_PWM2_Change_Duty, 0
$0622	$00F0			MOVWF	STACK_0
$0623	$01F1			CLRF	STACK_0+1
$0624	$158A			BSF	PCLATH, 3
$0625	$20AF			CALL	_mul_16x16_u
$0626	$118A			BCF	PCLATH, 3
$0627	$3006			MOVLW	6
$0628	$00F2			MOVWF	STACK_2
$0629	$0870			MOVF	STACK_0, 0
$062A	$00F8			MOVWF	STACK_8
$062B	$0871			MOVF	STACK_0+1, 0
$062C	$00F9			MOVWF	STACK_8+1
$062D	$0872			MOVF	STACK_2, 0
$062E	$	L_PWM2_Change_Duty_4:
$062E	$1903			BTFSC	STATUS, Z
$062F	$2E35			GOTO	L_PWM2_Change_Duty_5
$0630	$0CF9			RRF	STACK_8+1, 1
$0631	$0CF8			RRF	STACK_8, 1
$0632	$13F9			BCF	STACK_8+1, 7
$0633	$3FFF			ADDLW	255
$0634	$2E2E			GOTO	L_PWM2_Change_Duty_4
$0635	$	L_PWM2_Change_Duty_5:
;PWM_c21.ppas,90 :: 		
$0635	$0878			MOVF	STACK_8, 0
$0636	$00F0			MOVWF	STACK_0
$0637	$0879			MOVF	STACK_8+1, 0
$0638	$00F1			MOVWF	STACK_0+1
$0639	$0DF0			RLF	STACK_0, 1
$063A	$0DF1			RLF	STACK_0+1, 1
$063B	$1070			BCF	STACK_0, 0
$063C	$0DF0			RLF	STACK_0, 1
$063D	$0DF1			RLF	STACK_0+1, 1
$063E	$1070			BCF	STACK_0, 0
$063F	$0DF0			RLF	STACK_0, 1
$0640	$0DF1			RLF	STACK_0+1, 1
$0641	$1070			BCF	STACK_0, 0
$0642	$0DF0			RLF	STACK_0, 1
$0643	$0DF1			RLF	STACK_0+1, 1
$0644	$1070			BCF	STACK_0, 0
$0645	$3030			MOVLW	48
$0646	$0570			ANDWF	STACK_0, 0
$0647	$00F6			MOVWF	STACK_6
$0648	$0871			MOVF	STACK_0+1, 0
$0649	$00F7			MOVWF	STACK_6+1
$064A	$3000			MOVLW	0
$064B	$05F7			ANDWF	STACK_6+1, 1
;PWM_c21.ppas,91 :: 		
$064C	$0878			MOVF	STACK_8, 0
$064D	$00F0			MOVWF	STACK_0
$064E	$0879			MOVF	STACK_8+1, 0
$064F	$00F1			MOVWF	STACK_0+1
$0650	$0CF1			RRF	STACK_0+1, 1
$0651	$0CF0			RRF	STACK_0, 1
$0652	$13F1			BCF	STACK_0+1, 7
$0653	$0CF1			RRF	STACK_0+1, 1
$0654	$0CF0			RRF	STACK_0, 1
$0655	$13F1			BCF	STACK_0+1, 7
$0656	$0870			MOVF	STACK_0, 0
$0657	$009B			MOVWF	CCPR2L
;PWM_c21.ppas,92 :: 		
$0658	$300F			MOVLW	15
$0659	$059D			ANDWF	CCP2CON, 1
;PWM_c21.ppas,93 :: 		
$065A	$0876			MOVF	STACK_6, 0
$065B	$049D			IORWF	CCP2CON, 1
$065C	$	PWM_c21_L_13:
;PWM_c21.ppas,94 :: 		
$065C	$0008			RETURN
$090B	$	_pwm1_start:
;PWM_c21.ppas,62 :: 		
;PWM_c21.ppas,63 :: 		
$090B	$1303			BCF	STATUS, RP1
$090C	$1683			BSF	STATUS, RP0
$090D	$1107			BCF	TRISC, 2
;PWM_c21.ppas,64 :: 		
$090E	$1283			BCF	STATUS, RP0
$090F	$1512			BSF	T2CON, 2
;PWM_c21.ppas,65 :: 		
$0910	$300C			MOVLW	12
$0911	$0497			IORWF	CCP1CON, 1
$0912	$	PWM_c21_L_8:
;PWM_c21.ppas,66 :: 		
$0912	$0008			RETURN
$074B	$	_pwm2_start:
;PWM_c21.ppas,97 :: 		
;PWM_c21.ppas,98 :: 		
$074B	$1303			BCF	STATUS, RP1
$074C	$1683			BSF	STATUS, RP0
$074D	$1087			BCF	TRISC, 1
;PWM_c21.ppas,99 :: 		
$074E	$1283			BCF	STATUS, RP0
$074F	$1512			BSF	T2CON, 2
;PWM_c21.ppas,100 :: 		
$0750	$300C			MOVLW	12
$0751	$049D			IORWF	CCP2CON, 1
$0752	$	PWM_c21_L_14:
;PWM_c21.ppas,101 :: 		
$0752	$0008			RETURN
$0841	$	_adc_read:
;ADClib_A_C.ppas,12 :: 		
;ADClib_A_C.ppas,13 :: 		
$0841	$1303			BCF	STATUS, RP1
$0842	$1283			BCF	STATUS, RP0
$0843	$019F			CLRF	ADCON0, 1
;ADClib_A_C.ppas,14 :: 		
$0844	$30C0			MOVLW	192
$0845	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,15 :: 		
$0846	$3040			MOVLW	64
$0847	$1683			BSF	STATUS, RP0
$0848	$041F			IORWF	ADCON1, 0
$0849	$00F0			MOVWF	STACK_0
$084A	$0870			MOVF	STACK_0, 0
$084B	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,17 :: 		
$084C	$3080			MOVLW	128
$084D	$0470			IORWF	STACK_0, 0
$084E	$009F			MOVWF	ADCON1
;ADClib_A_C.ppas,18 :: 		
$084F	$1283			BCF	STATUS, RP0
$0850	$0846			MOVF	FARG_ADC_read, 0
$0851	$00F0			MOVWF	STACK_0
$0852	$0DF0			RLF	STACK_0, 1
$0853	$1070			BCF	STACK_0, 0
$0854	$0DF0			RLF	STACK_0, 1
$0855	$1070			BCF	STACK_0, 0
$0856	$0DF0			RLF	STACK_0, 1
$0857	$1070			BCF	STACK_0, 0
$0858	$0870			MOVF	STACK_0, 0
$0859	$049F			IORWF	ADCON0, 1
;ADClib_A_C.ppas,19 :: 		
$085A	$141F			BSF	ADCON0, 0
;ADClib_A_C.ppas,20 :: 		
$085B	$2113			CALL	_delay_22us
;ADClib_A_C.ppas,21 :: 		
$085C	$151F			BSF	ADCON0, 2
;ADClib_A_C.ppas,22 :: 		
$085D	$	ADClib_A_C_L_2:
$085D	$081F			MOVF	ADCON0, 0
$085E	$00F2			MOVWF	STACK_2
$085F	$3000			MOVLW	0
$0860	$1972			BTFSC	STACK_2, 2
$0861	$3001			MOVLW	1
$0862	$00F2			MOVWF	STACK_2
$0863	$0872			MOVF	STACK_2, 0
$0864	$3A01			XORLW	1
$0865	$1D03			BTFSS	STATUS, Z
$0866	$2869			GOTO	ADClib_A_C_L_3
;ADClib_A_C.ppas,23 :: 		
$0867	$0000			NOP
$0868	$285D			GOTO	ADClib_A_C_L_2
$0869	$	ADClib_A_C_L_3:
;ADClib_A_C.ppas,24 :: 		
$0869	$081E			MOVF	ADRESH, 0
$086A	$00F2			MOVWF	STACK_2
$086B	$01F3			CLRF	STACK_2+1
$086C	$0872			MOVF	STACK_2, 0
$086D	$00F3			MOVWF	STACK_2+1
$086E	$01F2			CLRF	STACK_2
$086F	$0872			MOVF	STACK_2, 0
$0870	$00C7			MOVWF	_adc_read_local_result
$0871	$0873			MOVF	STACK_2+1, 0
$0872	$00C8			MOVWF	_adc_read_local_result+1
;ADClib_A_C.ppas,25 :: 		
$0873	$1683			BSF	STATUS, RP0
$0874	$081E			MOVF	ADRESL, 0
$0875	$0472			IORWF	STACK_2, 0
$0876	$1283			BCF	STATUS, RP0
$0877	$00C7			MOVWF	_adc_read_local_result
$0878	$0873			MOVF	STACK_2+1, 0
$0879	$00C8			MOVWF	_adc_read_local_result+1
$087A	$3000			MOVLW	0
$087B	$04C8			IORWF	_adc_read_local_result+1, 1
;ADClib_A_C.ppas,26 :: 		
$087C	$101F			BCF	ADCON0, 0
$087D	$	ADClib_A_C_L_0:
;ADClib_A_C.ppas,27 :: 		
$087D	$0847			MOVF	_adc_read_local_result, 0
$087E	$00F0			MOVWF	STACK_0
$087F	$0848			MOVF	_adc_read_local_result+1, 0
$0880	$00F1			MOVWF	STACK_0+1
$0881	$0008			RETURN
$08FB	$	_pwm2_stop:
;PWM_c21.ppas,104 :: 		
;PWM_c21.ppas,105 :: 		
$08FB	$1303			BCF	STATUS, RP1
$08FC	$1683			BSF	STATUS, RP0
$08FD	$1487			BSF	TRISC, 1
;PWM_c21.ppas,107 :: 		
$08FE	$1283			BCF	STATUS, RP0
$08FF	$1112			BCF	T2CON, 2
$0900	$	PWM_c21_L_17:
;PWM_c21.ppas,108 :: 		
$0900	$30F0			MOVLW	240
$0901	$059D			ANDWF	CCP2CON, 1
$0902	$	PWM_c21_L_15:
;PWM_c21.ppas,109 :: 		
$0902	$0008			RETURN
$06A7	$	_pwm_change_duty:
;PWM_c21.ppas,18 :: 		
;PWM_c21.ppas,19 :: 		
$06A7	$1303			BCF	STATUS, RP1
$06A8	$1683			BSF	STATUS, RP0
$06A9	$0812			MOVF	PR2, 0
$06AA	$00F0			MOVWF	STACK_0
$06AB	$01F1			CLRF	STACK_0+1
$06AC	$0870			MOVF	STACK_0, 0
$06AD	$3F01			ADDLW	1
$06AE	$00F4			MOVWF	STACK_4
$06AF	$3000			MOVLW	0
$06B0	$1803			BTFSC	STATUS, C
$06B1	$3F01			ADDLW	1
$06B2	$0771			ADDWF	STACK_0+1, 0
$06B3	$00F5			MOVWF	STACK_4+1
$06B4	$1283			BCF	STATUS, RP0
$06B5	$0846			MOVF	FARG_PWM_Change_Duty, 0
$06B6	$00F0			MOVWF	STACK_0
$06B7	$01F1			CLRF	STACK_0+1
$06B8	$158A			BSF	PCLATH, 3
$06B9	$20AF			CALL	_mul_16x16_u
$06BA	$118A			BCF	PCLATH, 3
$06BB	$3006			MOVLW	6
$06BC	$00F2			MOVWF	STACK_2
$06BD	$0870			MOVF	STACK_0, 0
$06BE	$00F8			MOVWF	STACK_8
$06BF	$0871			MOVF	STACK_0+1, 0
$06C0	$00F9			MOVWF	STACK_8+1
$06C1	$0872			MOVF	STACK_2, 0
$06C2	$	L_PWM_Change_Duty_0:
$06C2	$1903			BTFSC	STATUS, Z
$06C3	$2EC9			GOTO	L_PWM_Change_Duty_1
$06C4	$0CF9			RRF	STACK_8+1, 1
$06C5	$0CF8			RRF	STACK_8, 1
$06C6	$13F9			BCF	STACK_8+1, 7
$06C7	$3FFF			ADDLW	255
$06C8	$2EC2			GOTO	L_PWM_Change_Duty_0
$06C9	$	L_PWM_Change_Duty_1:
;PWM_c21.ppas,20 :: 		
$06C9	$0878			MOVF	STACK_8, 0
$06CA	$00F0			MOVWF	STACK_0
$06CB	$0879			MOVF	STACK_8+1, 0
$06CC	$00F1			MOVWF	STACK_0+1
$06CD	$0DF0			RLF	STACK_0, 1
$06CE	$0DF1			RLF	STACK_0+1, 1
$06CF	$1070			BCF	STACK_0, 0
$06D0	$0DF0			RLF	STACK_0, 1
$06D1	$0DF1			RLF	STACK_0+1, 1
$06D2	$1070			BCF	STACK_0, 0
$06D3	$0DF0			RLF	STACK_0, 1
$06D4	$0DF1			RLF	STACK_0+1, 1
$06D5	$1070			BCF	STACK_0, 0
$06D6	$0DF0			RLF	STACK_0, 1
$06D7	$0DF1			RLF	STACK_0+1, 1
$06D8	$1070			BCF	STACK_0, 0
$06D9	$3030			MOVLW	48
$06DA	$0570			ANDWF	STACK_0, 0
$06DB	$00F6			MOVWF	STACK_6
$06DC	$0871			MOVF	STACK_0+1, 0
$06DD	$00F7			MOVWF	STACK_6+1
$06DE	$3000			MOVLW	0
$06DF	$05F7			ANDWF	STACK_6+1, 1
;PWM_c21.ppas,21 :: 		
$06E0	$0878			MOVF	STACK_8, 0
$06E1	$00F0			MOVWF	STACK_0
$06E2	$0879			MOVF	STACK_8+1, 0
$06E3	$00F1			MOVWF	STACK_0+1
$06E4	$0CF1			RRF	STACK_0+1, 1
$06E5	$0CF0			RRF	STACK_0, 1
$06E6	$13F1			BCF	STACK_0+1, 7
$06E7	$0CF1			RRF	STACK_0+1, 1
$06E8	$0CF0			RRF	STACK_0, 1
$06E9	$13F1			BCF	STACK_0+1, 7
$06EA	$0870			MOVF	STACK_0, 0
$06EB	$0095			MOVWF	CCPR1L
;PWM_c21.ppas,22 :: 		
$06EC	$300F			MOVLW	15
$06ED	$0597			ANDWF	CCP1CON, 1
;PWM_c21.ppas,23 :: 		
$06EE	$0876			MOVF	STACK_6, 0
$06EF	$0497			IORWF	CCP1CON, 1
$06F0	$	PWM_c21_L_1:
;PWM_c21.ppas,24 :: 		
$06F0	$0008			RETURN
$08F3	$	_pwm1_stop:
;PWM_c21.ppas,69 :: 		
;PWM_c21.ppas,70 :: 		
$08F3	$1303			BCF	STATUS, RP1
$08F4	$1683			BSF	STATUS, RP0
$08F5	$1507			BSF	TRISC, 2
;PWM_c21.ppas,72 :: 		
$08F6	$1283			BCF	STATUS, RP0
$08F7	$1112			BCF	T2CON, 2
$08F8	$	PWM_c21_L_11:
;PWM_c21.ppas,73 :: 		
$08F8	$30F0			MOVLW	240
$08F9	$0597			ANDWF	CCP1CON, 1
$08FA	$	PWM_c21_L_9:
;PWM_c21.ppas,74 :: 		
$08FA	$0008			RETURN
$037F	$	_longinttostr:
;conv.ppas,171 :: 		
;conv.ppas,172 :: 		
$037F	$1303			BCF	STATUS, RP1
$0380	$1283			BCF	STATUS, RP0
$0381	$0849			MOVF	FARG_LongIntToStr+3, 0
$0382	$3A80			XORLW	128
$0383	$1D03			BTFSS	STATUS, Z
$0384	$2B8F			GOTO	L_LongIntToStr_14
$0385	$0848			MOVF	FARG_LongIntToStr+2, 0
$0386	$3A00			XORLW	0
$0387	$1D03			BTFSS	STATUS, Z
$0388	$2B8F			GOTO	L_LongIntToStr_14
$0389	$0847			MOVF	FARG_LongIntToStr+1, 0
$038A	$3A00			XORLW	0
$038B	$1D03			BTFSS	STATUS, Z
$038C	$2B8F			GOTO	L_LongIntToStr_14
$038D	$0846			MOVF	FARG_LongIntToStr, 0
$038E	$3A00			XORLW	0
$038F	$	L_LongIntToStr_14:
$038F	$1D03			BTFSS	STATUS, Z
$0390	$2BB6			GOTO	conv_L_105
$0391	$	conv_L_104:
;conv.ppas,174 :: 		
$0391	$084A			MOVF	FARG_LongIntToStr+4, 0
$0392	$0084			MOVWF	FSR
$0393	$302D			MOVLW	45
$0394	$0080			MOVWF	INDF
$0395	$0A84			INCF	FSR, 1
$0396	$3032			MOVLW	50
$0397	$0080			MOVWF	INDF
$0398	$0A84			INCF	FSR, 1
$0399	$3031			MOVLW	49
$039A	$0080			MOVWF	INDF
$039B	$0A84			INCF	FSR, 1
$039C	$3034			MOVLW	52
$039D	$0080			MOVWF	INDF
$039E	$0A84			INCF	FSR, 1
$039F	$3037			MOVLW	55
$03A0	$0080			MOVWF	INDF
$03A1	$0A84			INCF	FSR, 1
$03A2	$3034			MOVLW	52
$03A3	$0080			MOVWF	INDF
$03A4	$0A84			INCF	FSR, 1
$03A5	$3038			MOVLW	56
$03A6	$0080			MOVWF	INDF
$03A7	$0A84			INCF	FSR, 1
$03A8	$3033			MOVLW	51
$03A9	$0080			MOVWF	INDF
$03AA	$0A84			INCF	FSR, 1
$03AB	$3036			MOVLW	54
$03AC	$0080			MOVWF	INDF
$03AD	$0A84			INCF	FSR, 1
$03AE	$3034			MOVLW	52
$03AF	$0080			MOVWF	INDF
$03B0	$0A84			INCF	FSR, 1
$03B1	$3038			MOVLW	56
$03B2	$0080			MOVWF	INDF
$03B3	$0A84			INCF	FSR, 1
$03B4	$0180			CLRF	INDF
;conv.ppas,175 :: 		
$03B5	$2C71			GOTO	conv_L_103
;conv.ppas,176 :: 		
$03B6	$	conv_L_105:
$03B6	$	conv_L_106:
;conv.ppas,178 :: 		
$03B6	$01CC			CLRF	_longinttostr_local_negative, 1
;conv.ppas,179 :: 		
$03B7	$3080			MOVLW	128
$03B8	$0649			XORWF	FARG_LongIntToStr+3, 0
$03B9	$00F0			MOVWF	STACK_0
$03BA	$3080			MOVLW	128
$03BB	$0270			SUBWF	STACK_0, 0
$03BC	$1D03			BTFSS	STATUS, Z
$03BD	$2BC8			GOTO	L_LongIntToStr_15
$03BE	$3000			MOVLW	0
$03BF	$0248			SUBWF	FARG_LongIntToStr+2, 0
$03C0	$1D03			BTFSS	STATUS, Z
$03C1	$2BC8			GOTO	L_LongIntToStr_15
$03C2	$3000			MOVLW	0
$03C3	$0247			SUBWF	FARG_LongIntToStr+1, 0
$03C4	$1D03			BTFSS	STATUS, Z
$03C5	$2BC8			GOTO	L_LongIntToStr_15
$03C6	$3000			MOVLW	0
$03C7	$0246			SUBWF	FARG_LongIntToStr, 0
$03C8	$	L_LongIntToStr_15:
$03C8	$1803			BTFSC	STATUS, C
$03C9	$2BE6			GOTO	conv_L_109
$03CA	$	conv_L_108:
;conv.ppas,181 :: 		
$03CA	$30FF			MOVLW	255
$03CB	$00CC			MOVWF	_longinttostr_local_negative
;conv.ppas,182 :: 		
$03CC	$01F0			CLRF	STACK_0
$03CD	$01F1			CLRF	STACK_0+1
$03CE	$01F2			CLRF	STACK_0+2
$03CF	$01F3			CLRF	STACK_0+3
$03D0	$0846			MOVF	FARG_LongIntToStr, 0
$03D1	$02F0			SUBWF	STACK_0, 1
$03D2	$0847			MOVF	FARG_LongIntToStr+1, 0
$03D3	$1C03			BTFSS	STATUS, C
$03D4	$0F47			INCFSZ	FARG_LongIntToStr+1, 0
$03D5	$02F1			SUBWF	STACK_0+1, 1
$03D6	$0848			MOVF	FARG_LongIntToStr+2, 0
$03D7	$1C03			BTFSS	STATUS, C
$03D8	$0F48			INCFSZ	FARG_LongIntToStr+2, 0
$03D9	$02F2			SUBWF	STACK_0+2, 1
$03DA	$0849			MOVF	FARG_LongIntToStr+3, 0
$03DB	$1C03			BTFSS	STATUS, C
$03DC	$0F49			INCFSZ	FARG_LongIntToStr+3, 0
$03DD	$02F3			SUBWF	STACK_0+3, 1
$03DE	$0870			MOVF	STACK_0, 0
$03DF	$00C6			MOVWF	FARG_LongIntToStr
$03E0	$0871			MOVF	STACK_0+1, 0
$03E1	$00C7			MOVWF	FARG_LongIntToStr+1
$03E2	$0872			MOVF	STACK_0+2, 0
$03E3	$00C8			MOVWF	FARG_LongIntToStr+2
$03E4	$0873			MOVF	STACK_0+3, 0
$03E5	$00C9			MOVWF	FARG_LongIntToStr+3
;conv.ppas,183 :: 		
$03E6	$	conv_L_109:
$03E6	$	conv_L_110:
;conv.ppas,185 :: 		
$03E6	$3001			MOVLW	1
$03E7	$00CB			MOVWF	_longinttostr_local_len
;conv.ppas,186 :: 		
$03E8	$0846			MOVF	FARG_LongIntToStr, 0
$03E9	$00CD			MOVWF	_longinttostr_local_tmpx
$03EA	$0847			MOVF	FARG_LongIntToStr+1, 0
$03EB	$00CE			MOVWF	_longinttostr_local_tmpx+1
$03EC	$0848			MOVF	FARG_LongIntToStr+2, 0
$03ED	$00CF			MOVWF	_longinttostr_local_tmpx+2
$03EE	$0849			MOVF	FARG_LongIntToStr+3, 0
$03EF	$00D0			MOVWF	_longinttostr_local_tmpx+3
;conv.ppas,187 :: 		
$03F0	$	conv_L_112:
$03F0	$3000			MOVLW	0
$03F1	$00F0			MOVWF	STACK_0
$03F2	$0650			XORWF	_longinttostr_local_tmpx+3, 0
$03F3	$1D03			BTFSS	STATUS, Z
$03F4	$2BFF			GOTO	L_LongIntToStr_16
$03F5	$0870			MOVF	STACK_0, 0
$03F6	$064F			XORWF	_longinttostr_local_tmpx+2, 0
$03F7	$1D03			BTFSS	STATUS, Z
$03F8	$2BFF			GOTO	L_LongIntToStr_16
$03F9	$0870			MOVF	STACK_0, 0
$03FA	$064E			XORWF	_longinttostr_local_tmpx+1, 0
$03FB	$1D03			BTFSS	STATUS, Z
$03FC	$2BFF			GOTO	L_LongIntToStr_16
$03FD	$084D			MOVF	_longinttostr_local_tmpx, 0
$03FE	$3A00			XORLW	0
$03FF	$	L_LongIntToStr_16:
$03FF	$1903			BTFSC	STATUS, Z
$0400	$2C19			GOTO	conv_L_113
;conv.ppas,189 :: 		
$0401	$300A			MOVLW	10
$0402	$00F4			MOVWF	STACK_4
$0403	$01F5			CLRF	STACK_4+1
$0404	$01F6			CLRF	STACK_4+2
$0405	$01F7			CLRF	STACK_4+3
$0406	$084D			MOVF	_longinttostr_local_tmpx, 0
$0407	$00F0			MOVWF	STACK_0
$0408	$084E			MOVF	_longinttostr_local_tmpx+1, 0
$0409	$00F1			MOVWF	STACK_0+1
$040A	$084F			MOVF	_longinttostr_local_tmpx+2, 0
$040B	$00F2			MOVWF	STACK_0+2
$040C	$0850			MOVF	_longinttostr_local_tmpx+3, 0
$040D	$00F3			MOVWF	STACK_0+3
$040E	$251B			CALL	_div_32x32_s
$040F	$0870			MOVF	STACK_0, 0
$0410	$00CD			MOVWF	_longinttostr_local_tmpx
$0411	$0871			MOVF	STACK_0+1, 0
$0412	$00CE			MOVWF	_longinttostr_local_tmpx+1
$0413	$0872			MOVF	STACK_0+2, 0
$0414	$00CF			MOVWF	_longinttostr_local_tmpx+2
$0415	$0873			MOVF	STACK_0+3, 0
$0416	$00D0			MOVWF	_longinttostr_local_tmpx+3
;conv.ppas,190 :: 		
$0417	$0ACB			INCF	_longinttostr_local_len, 1
;conv.ppas,191 :: 		
$0418	$2BF0			GOTO	conv_L_112
$0419	$	conv_L_113:
;conv.ppas,192 :: 		
$0419	$03CB			DECF	_longinttostr_local_len, 1
;conv.ppas,194 :: 		
$041A	$084A			MOVF	FARG_LongIntToStr+4, 0
$041B	$0084			MOVWF	FSR
$041C	$3020			MOVLW	32
$041D	$0080			MOVWF	INDF
$041E	$0A84			INCF	FSR, 1
$041F	$0080			MOVWF	INDF
$0420	$0A84			INCF	FSR, 1
$0421	$0080			MOVWF	INDF
$0422	$0A84			INCF	FSR, 1
$0423	$0080			MOVWF	INDF
$0424	$0A84			INCF	FSR, 1
$0425	$0080			MOVWF	INDF
$0426	$0A84			INCF	FSR, 1
$0427	$0080			MOVWF	INDF
$0428	$0A84			INCF	FSR, 1
$0429	$0080			MOVWF	INDF
$042A	$0A84			INCF	FSR, 1
$042B	$0080			MOVWF	INDF
$042C	$0A84			INCF	FSR, 1
$042D	$0080			MOVWF	INDF
$042E	$0A84			INCF	FSR, 1
$042F	$0080			MOVWF	INDF
$0430	$0A84			INCF	FSR, 1
$0431	$3030			MOVLW	48
$0432	$0080			MOVWF	INDF
$0433	$0A84			INCF	FSR, 1
$0434	$0180			CLRF	INDF
;conv.ppas,195 :: 		
$0435	$0384			DECF	FSR, 1
;conv.ppas,196 :: 		
$0436	$	conv_L_118:
$0436	$084B			MOVF	_longinttostr_local_len, 0
$0437	$3C00			SUBLW	0
$0438	$1803			BTFSC	STATUS, C
$0439	$2C6C			GOTO	conv_L_119
;conv.ppas,198 :: 		
$043A	$300A			MOVLW	10
$043B	$00F4			MOVWF	STACK_4
$043C	$01F5			CLRF	STACK_4+1
$043D	$01F6			CLRF	STACK_4+2
$043E	$01F7			CLRF	STACK_4+3
$043F	$0846			MOVF	FARG_LongIntToStr, 0
$0440	$00F0			MOVWF	STACK_0
$0441	$0847			MOVF	FARG_LongIntToStr+1, 0
$0442	$00F1			MOVWF	STACK_0+1
$0443	$0848			MOVF	FARG_LongIntToStr+2, 0
$0444	$00F2			MOVWF	STACK_0+2
$0445	$0849			MOVF	FARG_LongIntToStr+3, 0
$0446	$00F3			MOVWF	STACK_0+3
$0447	$251B			CALL	_div_32x32_s
$0448	$0878			MOVF	STACK_8, 0
$0449	$00F0			MOVWF	STACK_0
$044A	$0879			MOVF	STACK_9, 0
$044B	$00F1			MOVWF	STACK_1
$044C	$087A			MOVF	STACK_10, 0
$044D	$00F2			MOVWF	STACK_2
$044E	$087B			MOVF	STACK_11, 0
$044F	$00F3			MOVWF	STACK_3
;conv.ppas,199 :: 		
$0450	$3030			MOVLW	48
$0451	$0770			ADDWF	STACK_0, 0
$0452	$0080			MOVWF	INDF
;conv.ppas,200 :: 		
;conv.ppas,201 :: 		
$0453	$0384			DECF	FSR, 1
;conv.ppas,202 :: 		
$0454	$300A			MOVLW	10
$0455	$00F4			MOVWF	STACK_4
$0456	$01F5			CLRF	STACK_4+1
$0457	$01F6			CLRF	STACK_4+2
$0458	$01F7			CLRF	STACK_4+3
$0459	$0846			MOVF	FARG_LongIntToStr, 0
$045A	$00F0			MOVWF	STACK_0
$045B	$0847			MOVF	FARG_LongIntToStr+1, 0
$045C	$00F1			MOVWF	STACK_0+1
$045D	$0848			MOVF	FARG_LongIntToStr+2, 0
$045E	$00F2			MOVWF	STACK_0+2
$045F	$0849			MOVF	FARG_LongIntToStr+3, 0
$0460	$00F3			MOVWF	STACK_0+3
$0461	$251B			CALL	_div_32x32_s
$0462	$0870			MOVF	STACK_0, 0
$0463	$00C6			MOVWF	FARG_LongIntToStr
$0464	$0871			MOVF	STACK_0+1, 0
$0465	$00C7			MOVWF	FARG_LongIntToStr+1
$0466	$0872			MOVF	STACK_0+2, 0
$0467	$00C8			MOVWF	FARG_LongIntToStr+2
$0468	$0873			MOVF	STACK_0+3, 0
$0469	$00C9			MOVWF	FARG_LongIntToStr+3
;conv.ppas,203 :: 		
$046A	$03CB			DECF	_longinttostr_local_len, 1
;conv.ppas,204 :: 		
$046B	$2C36			GOTO	conv_L_118
$046C	$	conv_L_119:
;conv.ppas,205 :: 		
$046C	$084C			MOVF	_longinttostr_local_negative, 0
$046D	$1903			BTFSC	STATUS, Z
$046E	$2C71			GOTO	conv_L_123
$046F	$	conv_L_122:
;conv.ppas,207 :: 		
$046F	$302D			MOVLW	45
$0470	$0080			MOVWF	INDF
;conv.ppas,208 :: 		
$0471	$	conv_L_123:
$0471	$	conv_L_124:
$0471	$	conv_L_103:
;conv.ppas,209 :: 		
$0471	$0008			RETURN
$091A	$	_pwm1_init:
;PWM_c21.ppas,44 :: 		
;PWM_c21.ppas,45 :: 		
$091A	$1303			BCF	STATUS, RP1
$091B	$1283			BCF	STATUS, RP0
$091C	$0195			CLRF	CCPR1L, 1
;PWM_c21.ppas,46 :: 		
$091D	$1217			BCF	CCP1CON, 4
;PWM_c21.ppas,47 :: 		
$091E	$1297			BCF	CCP1CON, 5
$091F	$	PWM_c21_L_6:
;PWM_c21.ppas,48 :: 		
$091F	$0008			RETURN
$0920	$	_pwm2_init:
;PWM_c21.ppas,79 :: 		
;PWM_c21.ppas,80 :: 		
$0920	$1303			BCF	STATUS, RP1
$0921	$1283			BCF	STATUS, RP0
$0922	$019B			CLRF	CCPR2L, 1
;PWM_c21.ppas,81 :: 		
$0923	$121D			BCF	CCP2CON, 4
;PWM_c21.ppas,82 :: 		
$0924	$129D			BCF	CCP2CON, 5
$0925	$	PWM_c21_L_12:
;PWM_c21.ppas,83 :: 		
$0925	$0008			RETURN
$05B7	$	_div_16x16_s:
$05B7	$1303			BCF	STATUS, RP1
$05B8	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$05B9	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$05BA	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$05BB	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$05BC	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$05BD	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$05BE	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$05BF	$3400			RETLW	0
;math.ppas,356 :: 		
$05C0	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$05C1	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$05C2	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$05C3	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$05C4	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$05C5	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$05C6	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$05C7	$2DCD			GOTO	$+6
;math.ppas,367 :: 		
$05C8	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$05C9	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$05CA	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$05CB	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$05CC	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$05CD	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$05CE	$2DD4			GOTO	$+6
;math.ppas,376 :: 		
$05CF	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$05D0	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$05D1	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$05D2	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$05D3	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$05D4	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$05D5	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$05D6	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$05D7	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$05D8	$2DE9			GOTO	$+17
;math.ppas,388 :: 		
$05D9	$158A			BSF	PCLATH, 3
$05DA	$2082			CALL	_div_16x16_s_l
$05DB	$118A			BCF	PCLATH, 3
;math.ppas,390 :: 		
$05DC	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$05DD	$2DFE			GOTO	$+33
;math.ppas,393 :: 		
$05DE	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$05DF	$3400			RETLW	0
;math.ppas,396 :: 		
$05E0	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$05E1	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$05E2	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$05E3	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$05E4	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$05E5	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$05E6	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$05E7	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$05E8	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$05E9	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$05EA	$3400			RETLW	0
;math.ppas,410 :: 		
$05EB	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$05EC	$2DFA			GOTO	$+14
;math.ppas,412 :: 		
$05ED	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$05EE	$2DF6			GOTO	$+8
;math.ppas,414 :: 		
$05EF	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$05F0	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$05F1	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$05F2	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$05F3	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$05F4	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$05F5	$2DDE			GOTO	$-23
;math.ppas,421 :: 		
$05F6	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$05F7	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$05F8	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$05F9	$3400			RETLW	0
;math.ppas,426 :: 		
$05FA	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$05FB	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$05FC	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$05FD	$2DDB			GOTO	$-34
;math.ppas,431 :: 		
$05FE	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$05FF	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$0600	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$0601	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$0602	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$0603	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$0604	$2DDE			GOTO	$-38
;math.ppas,438 :: 		
$0605	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$0606	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$0607	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$0608	$2DDE			GOTO	$-42
;math.ppas,442 :: 		
$0609	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$060A	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$060B	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$060C	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$060D	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$060E	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$060F	$2DDE			GOTO	$-49
;math.ppas,449 :: 		
$0610	$0000			NOP
;math.ppas,450 :: 		
$0611	$34FF			RETLW	255
;math.ppas,451 :: 		
$0612	$	math_L_7:
;math.ppas,452 :: 		
$0612	$0008			RETURN
$06F1	$	_mul_16x16_s:
$06F1	$1303			BCF	STATUS, RP1
$06F2	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$06F3	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$06F4	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$06F5	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$06F6	$3080			MOVLW	128
;math.ppas,210 :: 		
$06F7	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$06F8	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$06F9	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$06FA	$2F01			GOTO	$+7
;math.ppas,215 :: 		
$06FB	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$06FC	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$06FD	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$06FE	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$06FF	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$0700	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$0701	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$0702	$2F09			GOTO	$+7
;math.ppas,224 :: 		
$0703	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$0704	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$0705	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$0706	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$0707	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$0708	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$0709	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$070A	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$070B	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$070C	$2F16			GOTO	$+10
;math.ppas,236 :: 		
$070D	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$070E	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$070F	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$0710	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$0711	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$0712	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$0713	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$0714	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$0715	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$0716	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$0717	$2F1E			GOTO	$+7
;math.ppas,249 :: 		
$0718	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$0719	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$071A	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$071B	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$071C	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$071D	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$071E	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$071F	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$0720	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$0721	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$0722	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$0723	$2F09			GOTO	$-26
;math.ppas,263 :: 		
$0724	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$0725	$2F31			GOTO	$+12
;math.ppas,266 :: 		
$0726	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$0727	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$0728	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$0729	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$072A	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$072B	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$072C	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$072D	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$072E	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$072F	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$0730	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$0731	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$0732	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$0733	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$0734	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$0735	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$0736	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$0737	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$0738	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$0739	$	math_L_5:
;math.ppas,288 :: 		
$0739	$0008			RETURN
$0004	$	_main:
;MOTEURBRAS.ppas,4 :: 		begin
;MOTEURBRAS.ppas,5 :: 		intcon:=$80;  // activation du convertisseur
$0004	$3080			MOVLW	128
$0005	$008B			MOVWF	INTCON
;MOTEURBRAS.ppas,6 :: 		LCD_config(portb,6,5,4,3,portb,0,1,2); // configuration de l'afficheur LCD
$0006	$3006			MOVLW	PORTB
$0007	$1303			BCF	STATUS, RP1
$0008	$1283			BCF	STATUS, RP0
$0009	$00C6			MOVWF	FARG_Lcd_Config
$000A	$3006			MOVLW	6
$000B	$00C7			MOVWF	FARG_Lcd_Config+1
$000C	$3005			MOVLW	5
$000D	$00C8			MOVWF	FARG_Lcd_Config+2
$000E	$3004			MOVLW	4
$000F	$00C9			MOVWF	FARG_Lcd_Config+3
$0010	$3003			MOVLW	3
$0011	$00CA			MOVWF	FARG_Lcd_Config+4
$0012	$3006			MOVLW	PORTB
$0013	$00CB			MOVWF	FARG_Lcd_Config+5
$0014	$01CC			CLRF	FARG_Lcd_Config+6, 1
$0015	$3001			MOVLW	1
$0016	$00CD			MOVWF	FARG_Lcd_Config+7
$0017	$3002			MOVLW	2
$0018	$00CE			MOVWF	FARG_Lcd_Config+8
$0019	$2132			CALL	_lcd_config
;MOTEURBRAS.ppas,7 :: 		lcd_cmd(LCD_CURSOR_OFF);
$001A	$300C			MOVLW	12
$001B	$00D2			MOVWF	FARG_Lcd_Cmd
$001C	$2472			CALL	_lcd_cmd
;MOTEURBRAS.ppas,8 :: 		TRISC:=0;
$001D	$1683			BSF	STATUS, RP0
$001E	$0187			CLRF	TRISC, 1
;MOTEURBRAS.ppas,9 :: 		lcd_out(1,1,'Consigne:');
$001F	$3001			MOVLW	1
$0020	$1283			BCF	STATUS, RP0
$0021	$00C6			MOVWF	FARG_Lcd_Out
$0022	$3001			MOVLW	1
$0023	$00C7			MOVWF	FARG_Lcd_Out+1
$0024	$3043			MOVLW	67
$0025	$00BC			MOVWF	?main_Local_Text+0
$0026	$306F			MOVLW	111
$0027	$00BD			MOVWF	?main_Local_Text+1
$0028	$306E			MOVLW	110
$0029	$00BE			MOVWF	?main_Local_Text+2
$002A	$3073			MOVLW	115
$002B	$00BF			MOVWF	?main_Local_Text+3
$002C	$3069			MOVLW	105
$002D	$00C0			MOVWF	?main_Local_Text+4
$002E	$3067			MOVLW	103
$002F	$00C1			MOVWF	?main_Local_Text+5
$0030	$306E			MOVLW	110
$0031	$00C2			MOVWF	?main_Local_Text+6
$0032	$3065			MOVLW	101
$0033	$00C3			MOVWF	?main_Local_Text+7
$0034	$303A			MOVLW	58
$0035	$00C4			MOVWF	?main_Local_Text+8
$0036	$01C5			CLRF	?main_Local_Text+9
$0037	$303C			MOVLW	?main_Local_Text
$0038	$00C8			MOVWF	FARG_Lcd_Out+2
$0039	$158A			BSF	PCLATH, 3
$003A	$2000			CALL	_lcd_out
$003B	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,10 :: 		lcd_out(2,1,'Sens    :');
$003C	$3002			MOVLW	2
$003D	$00C6			MOVWF	FARG_Lcd_Out
$003E	$3001			MOVLW	1
$003F	$00C7			MOVWF	FARG_Lcd_Out+1
$0040	$3053			MOVLW	83
$0041	$00BC			MOVWF	?main_Local_Text+0
$0042	$3065			MOVLW	101
$0043	$00BD			MOVWF	?main_Local_Text+1
$0044	$306E			MOVLW	110
$0045	$00BE			MOVWF	?main_Local_Text+2
$0046	$3073			MOVLW	115
$0047	$00BF			MOVWF	?main_Local_Text+3
$0048	$3020			MOVLW	32
$0049	$00C0			MOVWF	?main_Local_Text+4
$004A	$3020			MOVLW	32
$004B	$00C1			MOVWF	?main_Local_Text+5
$004C	$3020			MOVLW	32
$004D	$00C2			MOVWF	?main_Local_Text+6
$004E	$3020			MOVLW	32
$004F	$00C3			MOVWF	?main_Local_Text+7
$0050	$303A			MOVLW	58
$0051	$00C4			MOVWF	?main_Local_Text+8
$0052	$01C5			CLRF	?main_Local_Text+9
$0053	$303C			MOVLW	?main_Local_Text
$0054	$00C8			MOVWF	FARG_Lcd_Out+2
$0055	$158A			BSF	PCLATH, 3
$0056	$2000			CALL	_lcd_out
$0057	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,11 :: 		pwm1_init(500);   //  activation du MLI
$0058	$1012			BCF	T2CON, T2CKPS0
$0059	$1092			BCF	T2CON, T2CKPS1
$005A	$1412			BSF	T2CON, T2CKPS0
$005B	$1492			BSF	T2CON, T2CKPS1
$005C	$307C			MOVLW	124
$005D	$1683			BSF	STATUS, RP0
$005E	$0092			MOVWF	PR2
$005F	$158A			BSF	PCLATH, 3
$0060	$211A			CALL	_pwm1_init
$0061	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,12 :: 		pwm2_init(500);   //  activation du MLI
$0062	$1012			BCF	T2CON, T2CKPS0
$0063	$1092			BCF	T2CON, T2CKPS1
$0064	$1412			BSF	T2CON, T2CKPS0
$0065	$1492			BSF	T2CON, T2CKPS1
$0066	$307C			MOVLW	124
$0067	$1683			BSF	STATUS, RP0
$0068	$0092			MOVWF	PR2
$0069	$158A			BSF	PCLATH, 3
$006A	$2120			CALL	_pwm2_init
$006B	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,13 :: 		pwm1_change_duty(0); // changement du rapport cyclique
$006C	$01C6			CLRF	FARG_PWM1_Change_Duty, 1
$006D	$265D			CALL	_pwm1_change_duty
;MOTEURBRAS.ppas,14 :: 		pwm2_change_duty(0); // changement du rapport cyclique
$006E	$01C6			CLRF	FARG_PWM2_Change_Duty, 1
$006F	$2613			CALL	_pwm2_change_duty
;MOTEURBRAS.ppas,15 :: 		pwm1_start;
$0070	$158A			BSF	PCLATH, 3
$0071	$210B			CALL	_pwm1_start
$0072	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,16 :: 		pwm2_start;
$0073	$274B			CALL	_pwm2_start
;MOTEURBRAS.ppas,17 :: 		while (true) do
$0074	$	MOTEURBRAS_L_2:
;MOTEURBRAS.ppas,19 :: 		x:=adc_read(0);
$0074	$01C6			CLRF	FARG_ADC_read, 1
$0075	$158A			BSF	PCLATH, 3
$0076	$2041			CALL	_adc_read
$0077	$118A			BCF	PCLATH, 3
$0078	$0870			MOVF	STACK_0, 0
$0079	$00AB			MOVWF	_x
$007A	$0871			MOVF	STACK_0+1, 0
$007B	$00AC			MOVWF	_x+1
;MOTEURBRAS.ppas,20 :: 		if x < 512 then
$007C	$3080			MOVLW	128
$007D	$0671			XORWF	STACK_0+1, 0
$007E	$00F2			MOVWF	STACK_2
$007F	$3080			MOVLW	128
$0080	$3A02			XORLW	2
$0081	$0272			SUBWF	STACK_2, 0
$0082	$1D03			BTFSS	STATUS, Z
$0083	$2886			GOTO	L_main_0
$0084	$3000			MOVLW	0
$0085	$0270			SUBWF	STACK_0, 0
$0086	$	L_main_0:
$0086	$1803			BTFSC	STATUS, C
$0087	$28B5			GOTO	MOTEURBRAS_L_7
$0088	$	MOTEURBRAS_L_6:
;MOTEURBRAS.ppas,22 :: 		vitesse:= 255- (x div 2);
$0088	$3002			MOVLW	2
$0089	$00F4			MOVWF	STACK_4
$008A	$01F5			CLRF	STACK_4+1
$008B	$082B			MOVF	_x, 0
$008C	$00F0			MOVWF	STACK_0
$008D	$082C			MOVF	_x+1, 0
$008E	$00F1			MOVWF	STACK_0+1
$008F	$25B7			CALL	_div_16x16_s
$0090	$0870			MOVF	STACK_0, 0
$0091	$3CFF			SUBLW	255
$0092	$00AD			MOVWF	_vitesse
$0093	$0871			MOVF	STACK_0+1, 0
$0094	$1C03			BTFSS	STATUS, C
$0095	$3F01			ADDLW	1
$0096	$3C00			SUBLW	0
$0097	$00AE			MOVWF	_vitesse+1
;MOTEURBRAS.ppas,23 :: 		pwm2_stop;
$0098	$158A			BSF	PCLATH, 3
$0099	$20FB			CALL	_pwm2_stop
$009A	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,24 :: 		pwm1_start;
$009B	$158A			BSF	PCLATH, 3
$009C	$210B			CALL	_pwm1_start
$009D	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,25 :: 		pwm_change_duty(vitesse);
$009E	$082D			MOVF	_vitesse, 0
$009F	$00C6			MOVWF	FARG_PWM_Change_Duty
$00A0	$26A7			CALL	_pwm_change_duty
;MOTEURBRAS.ppas,26 :: 		vitesse:=(vitesse * 100)div 255;
$00A1	$082D			MOVF	_vitesse, 0
$00A2	$00F0			MOVWF	STACK_0
$00A3	$082E			MOVF	_vitesse+1, 0
$00A4	$00F1			MOVWF	STACK_0+1
$00A5	$3064			MOVLW	100
$00A6	$00F4			MOVWF	STACK_4
$00A7	$01F5			CLRF	STACK_4+1
$00A8	$26F1			CALL	_mul_16x16_s
$00A9	$30FF			MOVLW	255
$00AA	$00F4			MOVWF	STACK_4
$00AB	$01F5			CLRF	STACK_4+1
$00AC	$25B7			CALL	_div_16x16_s
$00AD	$0870			MOVF	STACK_0, 0
$00AE	$00AD			MOVWF	_vitesse
$00AF	$0871			MOVF	STACK_0+1, 0
$00B0	$00AE			MOVWF	_vitesse+1
;MOTEURBRAS.ppas,27 :: 		sens := 1;
$00B1	$3001			MOVLW	1
$00B2	$00AF			MOVWF	_sens
$00B3	$01B0			CLRF	_sens+1
;MOTEURBRAS.ppas,28 :: 		end
$00B4	$28DF			GOTO	MOTEURBRAS_L_8
;MOTEURBRAS.ppas,29 :: 		else
$00B5	$	MOTEURBRAS_L_7:
;MOTEURBRAS.ppas,31 :: 		pwm1_stop;
$00B5	$158A			BSF	PCLATH, 3
$00B6	$20F3			CALL	_pwm1_stop
$00B7	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,32 :: 		pwm2_start;
$00B8	$274B			CALL	_pwm2_start
;MOTEURBRAS.ppas,33 :: 		vitesse:=(x-512)div 2;
$00B9	$3000			MOVLW	0
$00BA	$022B			SUBWF	_x, 0
$00BB	$00F0			MOVWF	STACK_0
$00BC	$3002			MOVLW	2
$00BD	$1C03			BTFSS	STATUS, C
$00BE	$3F01			ADDLW	1
$00BF	$022C			SUBWF	_x+1, 0
$00C0	$00F1			MOVWF	STACK_0+1
$00C1	$3002			MOVLW	2
$00C2	$00F4			MOVWF	STACK_4
$00C3	$01F5			CLRF	STACK_4+1
$00C4	$25B7			CALL	_div_16x16_s
$00C5	$0870			MOVF	STACK_0, 0
$00C6	$00AD			MOVWF	_vitesse
$00C7	$0871			MOVF	STACK_0+1, 0
$00C8	$00AE			MOVWF	_vitesse+1
;MOTEURBRAS.ppas,34 :: 		pwm2_change_duty(vitesse);
$00C9	$0870			MOVF	STACK_0, 0
$00CA	$00C6			MOVWF	FARG_PWM2_Change_Duty
$00CB	$2613			CALL	_pwm2_change_duty
;MOTEURBRAS.ppas,35 :: 		vitesse:=(vitesse * 100)div 255;
$00CC	$082D			MOVF	_vitesse, 0
$00CD	$00F0			MOVWF	STACK_0
$00CE	$082E			MOVF	_vitesse+1, 0
$00CF	$00F1			MOVWF	STACK_0+1
$00D0	$3064			MOVLW	100
$00D1	$00F4			MOVWF	STACK_4
$00D2	$01F5			CLRF	STACK_4+1
$00D3	$26F1			CALL	_mul_16x16_s
$00D4	$30FF			MOVLW	255
$00D5	$00F4			MOVWF	STACK_4
$00D6	$01F5			CLRF	STACK_4+1
$00D7	$25B7			CALL	_div_16x16_s
$00D8	$0870			MOVF	STACK_0, 0
$00D9	$00AD			MOVWF	_vitesse
$00DA	$0871			MOVF	STACK_0+1, 0
$00DB	$00AE			MOVWF	_vitesse+1
;MOTEURBRAS.ppas,36 :: 		sens := 2;
$00DC	$3002			MOVLW	2
$00DD	$00AF			MOVWF	_sens
$00DE	$01B0			CLRF	_sens+1
;MOTEURBRAS.ppas,37 :: 		end;
$00DF	$	MOTEURBRAS_L_8:
;MOTEURBRAS.ppas,38 :: 		longinttostr(vitesse,txt);
$00DF	$082D			MOVF	_vitesse, 0
$00E0	$00C6			MOVWF	FARG_LongIntToStr
$00E1	$082E			MOVF	_vitesse+1, 0
$00E2	$00C7			MOVWF	FARG_LongIntToStr+1
$00E3	$3000			MOVLW	0
$00E4	$1BC7			BTFSC	FARG_LongIntToStr+1, 7
$00E5	$30FF			MOVLW	255
$00E6	$00C8			MOVWF	FARG_LongIntToStr+2
$00E7	$00C9			MOVWF	FARG_LongIntToStr+3
$00E8	$3031			MOVLW	_txt
$00E9	$00CA			MOVWF	FARG_LongIntToStr+4
$00EA	$237F			CALL	_longinttostr
;MOTEURBRAS.ppas,39 :: 		lcd_out(1,10,txt);
$00EB	$3001			MOVLW	1
$00EC	$00C6			MOVWF	FARG_Lcd_Out
$00ED	$300A			MOVLW	10
$00EE	$00C7			MOVWF	FARG_Lcd_Out+1
$00EF	$3031			MOVLW	_txt
$00F0	$00C8			MOVWF	FARG_Lcd_Out+2
$00F1	$158A			BSF	PCLATH, 3
$00F2	$2000			CALL	_lcd_out
$00F3	$118A			BCF	PCLATH, 3
;MOTEURBRAS.ppas,40 :: 		if sens = 1 then   lcd_out(2,10,'   1  ');
$00F4	$3000			MOVLW	0
$00F5	$0630			XORWF	_sens+1, 0
$00F6	$1D03			BTFSS	STATUS, Z
$00F7	$28FA			GOTO	L_main_1
$00F8	$3001			MOVLW	1
$00F9	$062F			XORWF	_sens, 0
$00FA	$	L_main_1:
$00FA	$1D03			BTFSS	STATUS, Z
$00FB	$2912			GOTO	MOTEURBRAS_L_10
$00FC	$	MOTEURBRAS_L_9:
$00FC	$3002			MOVLW	2
$00FD	$00C6			MOVWF	FARG_Lcd_Out
$00FE	$300A			MOVLW	10
$00FF	$00C7			MOVWF	FARG_Lcd_Out+1
$0100	$3020			MOVLW	32
$0101	$00BC			MOVWF	?main_Local_Text+0
$0102	$3020			MOVLW	32
$0103	$00BD			MOVWF	?main_Local_Text+1
$0104	$3020			MOVLW	32
$0105	$00BE			MOVWF	?main_Local_Text+2
$0106	$3031			MOVLW	49
$0107	$00BF			MOVWF	?main_Local_Text+3
$0108	$3020			MOVLW	32
$0109	$00C0			MOVWF	?main_Local_Text+4
$010A	$3020			MOVLW	32
$010B	$00C1			MOVWF	?main_Local_Text+5
$010C	$01C2			CLRF	?main_Local_Text+6
$010D	$303C			MOVLW	?main_Local_Text
$010E	$00C8			MOVWF	FARG_Lcd_Out+2
$010F	$158A			BSF	PCLATH, 3
$0110	$2000			CALL	_lcd_out
$0111	$118A			BCF	PCLATH, 3
$0112	$	MOTEURBRAS_L_10:
$0112	$	MOTEURBRAS_L_11:
;MOTEURBRAS.ppas,41 :: 		if sens = 2 then   lcd_out(2,10,'   2  ');
$0112	$3000			MOVLW	0
$0113	$0630			XORWF	_sens+1, 0
$0114	$1D03			BTFSS	STATUS, Z
$0115	$2918			GOTO	L_main_2
$0116	$3002			MOVLW	2
$0117	$062F			XORWF	_sens, 0
$0118	$	L_main_2:
$0118	$1D03			BTFSS	STATUS, Z
$0119	$2930			GOTO	MOTEURBRAS_L_13
$011A	$	MOTEURBRAS_L_12:
$011A	$3002			MOVLW	2
$011B	$00C6			MOVWF	FARG_Lcd_Out
$011C	$300A			MOVLW	10
$011D	$00C7			MOVWF	FARG_Lcd_Out+1
$011E	$3020			MOVLW	32
$011F	$00BC			MOVWF	?main_Local_Text+0
$0120	$3020			MOVLW	32
$0121	$00BD			MOVWF	?main_Local_Text+1
$0122	$3020			MOVLW	32
$0123	$00BE			MOVWF	?main_Local_Text+2
$0124	$3032			MOVLW	50
$0125	$00BF			MOVWF	?main_Local_Text+3
$0126	$3020			MOVLW	32
$0127	$00C0			MOVWF	?main_Local_Text+4
$0128	$3020			MOVLW	32
$0129	$00C1			MOVWF	?main_Local_Text+5
$012A	$01C2			CLRF	?main_Local_Text+6
$012B	$303C			MOVLW	?main_Local_Text
$012C	$00C8			MOVWF	FARG_Lcd_Out+2
$012D	$158A			BSF	PCLATH, 3
$012E	$2000			CALL	_lcd_out
$012F	$118A			BCF	PCLATH, 3
$0130	$	MOTEURBRAS_L_13:
$0130	$	MOTEURBRAS_L_14:
;MOTEURBRAS.ppas,44 :: 		end;
$0130	$2874			GOTO	MOTEURBRAS_L_2
;MOTEURBRAS.ppas,45 :: 		end.
$0131	$2931			GOTO	$
